// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef NAOSIMULATIONMODELLENTWURF_ENTWURF_NAOVIEW_ROBOTERANZEIGE_KOPFANZEIGE_KOPFZEICHNER_H
#define NAOSIMULATIONMODELLENTWURF_ENTWURF_NAOVIEW_ROBOTERANZEIGE_KOPFANZEIGE_KOPFZEICHNER_H

/************************************************************
 ArmZeichner class header
 ************************************************************/

#include "NaoSimulation/Entwurf/NaoView/Roboteranzeige/Kopfanzeige/Pkg_Kopfanzeige.h"
#include "NaoSimulation/Entwurf/NaoView/Roboteranzeige/Koerperteilanzeige/KoerperteilZeichner.h"
#include "NaoSimulation/Modellierung/Roboterverwaltung/Kopf/Kopf.h"
#include "NaoSimulation/Modellierung/Roboterverwaltung/Kopf/Schaedel.h"
#include "NaoSimulation/Modellierung/Roboterverwaltung/Kopf/Halsgelenk.h"

/*
namespace NaoSimulation {
namespace Modellierung {
namespace Roboterverwaltung {
namespace Kopf {
class Kopf;
}
}
}
}
*/
namespace NaoSimulation {
namespace Entwurf {
namespace NaoView {
namespace Roboteranzeige {
namespace Kopfanzeige {

/************************************************************/
/**
 * 
 */
class KopfZeichner {
public:
	static void zeichneKopf(::NaoSimulation::Modellierung::Roboterverwaltung::Kopf::Kopf* kopf);
};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Kopfanzeige
} // of namespace Roboteranzeige
} // of namespace NaoView
} // of namespace Entwurf
} // of namespace NaoSimulation

/************************************************************
 End of KopfZeichner class header
 ************************************************************/

#endif
