// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define NaoSimulation_Entwurf_NaoView_Roboteranzeige_Kopfanzeige_KopfZeichner_BODY

/************************************************************
 KopfZeichner class body
 ************************************************************/

// include associated header file
#include "NaoSimulation/Entwurf/NaoView/Roboteranzeige/Kopfanzeige/KopfZeichner.h"

// Derived includes directives
#include "NaoSimulation/Modellierung/Roboterverwaltung/Kopf/Kopf.h"

namespace NaoSimulation {
namespace Entwurf {
namespace NaoView {
namespace Roboteranzeige {
namespace Kopfanzeige {


void KopfZeichner::zeichneKopf(::NaoSimulation::Modellierung::Roboterverwaltung::Kopf::Kopf* kopf) {
	// Zeichne Schaedel
	NaoSimulation::Entwurf::NaoView::Roboteranzeige::Koerperteilanzeige::KoerperteilZeichner::zeichneKoerperteil(*kopf->getSchaedel());
}

} // of namespace Kopfanzeige
} // of namespace Roboteranzeige
} // of namespace NaoView
} // of namespace Entwurf
} // of namespace NaoSimulation

/************************************************************
 End of KopfZeichner class body
 ************************************************************/
