// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef NAOSIMULATION_MODELLIERUNG_ROBOTERVERWALTUNG_BEWEGE_GELENK_H
#define NAOSIMULATION_MODELLIERUNG_ROBOTERVERWALTUNG_BEWEGE_GELENK_H

/************************************************************
 bewege_Gelenk class header
 ************************************************************/

#include "NaoSimulation/Modellierung/Roboterverwaltung/Pkg_Roboterverwaltung.h"

namespace NaoSimulation {
namespace Modellierung {
namespace Roboterverwaltung {

/************************************************************/
/**
 * 
 */
class bewege_Gelenk {

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Roboterverwaltung
} // of namespace Modellierung
} // of namespace NaoSimulation

/************************************************************
 End of bewege_Gelenk class header
 ************************************************************/

#endif
