// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef NAOSIMULATION_MODELLIERUNG_ROBOTERVERWALTUNG_FREIHEITSGRAD_H
#define NAOSIMULATION_MODELLIERUNG_ROBOTERVERWALTUNG_FREIHEITSGRAD_H

/************************************************************
 Freiheitsgrad class header
 ************************************************************/

//#include "NaoSimulation/Modellierung/Roboterverwaltung/Pkg_Roboterverwaltung.h"

#include "../../../PrimitiveTypes/Pkg_PrimitiveTypes.h"

namespace NaoSimulation {
namespace Modellierung {
namespace Roboterverwaltung {

/************************************************************/
/**
 * 
 */
class Freiheitsgrad {
public:

	/**
	 * 
	 * @param winkel 
	 * @param winkel_min 
	 * @param winkel_max 
	 * @return result 
	 */
	Freiheitsgrad erzeugeFreiheitsgrad(::PrimitiveTypes::Real /*in*/winkel,
			::PrimitiveTypes::Real /*in*/winkel_min,
			::PrimitiveTypes::Real /*in*/winkel_max);

	Freiheitsgrad(::PrimitiveTypes::Real winkel, ::PrimitiveTypes::Real winkel_min, ::PrimitiveTypes::Real winkel_max):
		winkel(winkel), winkel_min(winkel_min), winkel_max(winkel_max) {}

	/**
	 * 
	 * @return result 
	 */
	::PrimitiveTypes::Real getWinkel();

	/**
	 * 
	 * @return result 
	 */
	::PrimitiveTypes::Real getWinkelMin();

	/**
	 * 
	 * @return result 
	 */
	::PrimitiveTypes::Real getWinkelMax();

	/**
	 * 
	 * @param winkel 
	 */
	void setWinkel(::PrimitiveTypes::Real /*in*/winkel);

private:

	/**
	 * 
	 */
	::PrimitiveTypes::Real winkel;

	/**
	 * 
	 */
	::PrimitiveTypes::Real winkel_min;

	/**
	 * 
	 */
	::PrimitiveTypes::Real winkel_max;
};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Roboterverwaltung
} // of namespace Modellierung
} // of namespace NaoSimulation

/************************************************************
 End of Freiheitsgrad class header
 ************************************************************/

#endif
