// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define NaoSimulation_Modellierung_Roboterverwaltung_Freiheitsgrad_BODY

/************************************************************
 Freiheitsgrad class body
 ************************************************************/

// include associated header file
#include "Freiheitsgrad.h"

// Derived includes directives

namespace NaoSimulation {
namespace Modellierung {
namespace Roboterverwaltung {

// static attributes (if any)

/**
 * 
 * @param winkel 
 * @param winkel_min 
 * @param winkel_max 
 * @return result 
 */
Freiheitsgrad Freiheitsgrad::erzeugeFreiheitsgrad(
		::PrimitiveTypes::Real /*in*/winkel,
		::PrimitiveTypes::Real /*in*/winkel_min,
		::PrimitiveTypes::Real /*in*/winkel_max) {
	Freiheitsgrad fg(winkel, winkel_min, winkel_max);
	return fg;
}

/**
 * 
 * @return result 
 */
::PrimitiveTypes::Real Freiheitsgrad::getWinkel() {
	return winkel;
}

/**
 * 
 * @return result 
 */
::PrimitiveTypes::Real Freiheitsgrad::getWinkelMin() {
	return winkel_min;
}

/**
 * 
 * @return result 
 */
::PrimitiveTypes::Real Freiheitsgrad::getWinkelMax() {
	return winkel_max;
}

/**
 * 
 * @param winkel 
 */
void Freiheitsgrad::setWinkel(::PrimitiveTypes::Real /*in*/winkel) {
	this->winkel = winkel;
}

} // of namespace Roboterverwaltung
} // of namespace Modellierung
} // of namespace NaoSimulation

/************************************************************
 End of Freiheitsgrad class body
 ************************************************************/
