// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef NAOSIMULATION_MODELLIERUNG_ROBOTERVERWALTUNG_KOPF_BEWEGE_KOPFGELENK_H
#define NAOSIMULATION_MODELLIERUNG_ROBOTERVERWALTUNG_KOPF_BEWEGE_KOPFGELENK_H

/************************************************************
 bewege_Kopfgelenk class header
 ************************************************************/

#include "NaoSimulation/Modellierung/Roboterverwaltung/Kopf/Pkg_Kopf.h"

#include "NaoSimulation/Modellierung/Roboterverwaltung/bewege_Gelenk.h"

namespace NaoSimulation {
namespace Modellierung {
namespace Roboterverwaltung {
namespace Kopf {

/************************************************************/
/**
 * 
 */
class bewege_Kopfgelenk: public ::NaoSimulation::Modellierung::Roboterverwaltung::bewege_Gelenk {

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Kopf
} // of namespace Roboterverwaltung
} // of namespace Modellierung
} // of namespace NaoSimulation

/************************************************************
 End of bewege_Kopfgelenk class header
 ************************************************************/

#endif
