// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef NAOSIMULATION_MODELLIERUNG_ROBOTERVERWALTUNG_KOPF_BEWEGE_HALSGELENK_H
#define NAOSIMULATION_MODELLIERUNG_ROBOTERVERWALTUNG_KOPF_BEWEGE_HALSGELENK_H

/************************************************************
 bewege_Halsgelenk class header
 ************************************************************/

#include "NaoSimulation/Modellierung/Roboterverwaltung/Kopf/Pkg_Kopf.h"

#include "NaoSimulation/Modellierung/Roboterverwaltung/Kopf/bewege_Kopfgelenk.h"

namespace NaoSimulation {
namespace Modellierung {
namespace Roboterverwaltung {
namespace Kopf {

/************************************************************/
/**
 * 
 */
class bewege_Halsgelenk {

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Kopf
} // of namespace Roboterverwaltung
} // of namespace Modellierung
} // of namespace NaoSimulation

/************************************************************
 End of bewege_Halsgelenk class header
 ************************************************************/

#endif
