// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef NAOSIMULATION_MODELLIERUNG_ROBOTERVERWALTUNG_KOPF_KOPF_H
#define NAOSIMULATION_MODELLIERUNG_ROBOTERVERWALTUNG_KOPF_KOPF_H

/************************************************************
 Kopf class header
 ************************************************************/

//#include "NaoSimulation/Modellierung/Roboterverwaltung/Kopf/Pkg_Kopf.h"

#include "Schaedel.h"
#include "NaoSimulation/Modellierung/Roboterverwaltung/Rumpf/Torso.h"
#include "Halsgelenk.h"



namespace NaoSimulation {
namespace Modellierung {
namespace Roboterverwaltung {
namespace Kopf {
using namespace Rumpf;
/************************************************************/
/**
 * 
 */
class Kopf : public NaoSimulation::Entwurf::NaoModel::BewegungsManagement::BewegbaresObjekt {
public:

	// Copy-Konstruktor
	Kopf(Kopf& kopf) :
		schaedel(new Schaedel(*kopf.getSchaedel())),
		halsgelenk(new Halsgelenk(*kopf.getHalsgelenk())) {}
		

	// Konstruktor
	Kopf(Schaedel* schaedel, Torso* torso, Halsgelenk* halsgelenk) : 
		schaedel(schaedel), torso(torso), halsgelenk(halsgelenk) {}

	// Destruktor
	~Kopf();

	static Kopf* erzeugeKopf(
		Schaedel *schaedel,
		Torso *torso,
		Halsgelenk *halsgelenk,
		NaoSimulation::Entwurf::NaoModel::ODE::dWorldID welt
	);

	Schaedel* getSchaedel();

	Torso* getTorso();

	Halsgelenk* getHalsgelenk();

	// ueberschreibe die Std-Implementierung fuer bewegbare Objekte
	bool inBewegung() override;

private:

	/**
	 * 
	 */
	Schaedel *schaedel;

	/**
	 * 
	 */
	Torso *torso;

	/**
	 * 
	 */
	Halsgelenk *halsgelenk;
};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Arm
} // of namespace Roboterverwaltung
} // of namespace Modellierung
} // of namespace NaoSimulation

/************************************************************
 End of Arm class header
 ************************************************************/

#endif
