// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef NAOSIMULATION_MODELLIERUNG_ROBOTERVERWALTUNG_KOPF_SCHAEDEL_H
#define NAOSIMULATION_MODELLIERUNG_ROBOTERVERWALTUNG_KOPF_SCHAEDEL_H

/************************************************************
 Schaedel class header
 ************************************************************/

//#include "NaoSimulation/Modellierung/Roboterverwaltung/Kopf/Pkg_Kopf.h"

#include "../../../Entwurf/NaoModel/Koerperteile/Koerperteil.h"
#include "../../Params/RoboterParamSettings.h"


namespace NaoSimulation {
namespace Modellierung {
namespace Roboterverwaltung {
namespace Kopf {

/************************************************************/
/**
 * 
 */
class Schaedel: public ::NaoSimulation::Entwurf::NaoModel::Koerperteile::Koerperteil {
public:

	// Konstruktor
	Schaedel() : Koerperteil() {}

	static Schaedel* erzeugeSchaedel(NaoSimulation::Entwurf::NaoModel::ODE::dWorldID welt);
};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Kopf
} // of namespace Roboterverwaltung
} // of namespace Modellierung
} // of namespace NaoSimulation

/************************************************************
 End of Schaedel class header
 ************************************************************/

#endif
