// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define NaoSimulation_Modellierung_Roboterverwaltung_Kopf_Schaedel_BODY

/************************************************************
 Fuss class body
 ************************************************************/

// include associated header file
#include "Schaedel.h"

// Derived includes directives

namespace NaoSimulation {
namespace Modellierung {
namespace Roboterverwaltung {
namespace Kopf {

Schaedel* Schaedel::erzeugeSchaedel(NaoSimulation::Entwurf::NaoModel::ODE::dWorldID welt) {
    Schaedel* schaedel = new Schaedel();
    schaedel->setHoehe(schaedelParams.hoehe);
    schaedel->setRadius(schaedelParams.radius);
    schaedel->setOdeKoerperteil(NaoSimulation::Entwurf::NaoModel::ODE::erzeugeODEBody(
        schaedelParams.masse,
        schaedelParams.position,
        schaedelParams.ausrichtung,
        schaedelParams.radius,
        schaedelParams.hoehe,
        welt
    ));

    return schaedel;
}


} // of namespace Kopf
} // of namespace Roboterverwaltung
} // of namespace Modellierung
} // of namespace NaoSimulation

/************************************************************
 End of Schaedel class body
 ************************************************************/
