// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef NAOSIMULATION_MODELLIERUNG_NUTZER_H
#define NAOSIMULATION_MODELLIERUNG_NUTZER_H

/************************************************************
 Nutzer class header
 ************************************************************/

#include "NaoSimulation/Modellierung/Pkg_Modellierung.h"

namespace NaoSimulation {
namespace Modellierung {

/************************************************************/
/**
 * 
 */
class Nutzer {

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Modellierung
} // of namespace NaoSimulation

/************************************************************
 End of Nutzer class header
 ************************************************************/

#endif
