// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef NAOSIMULATIONMODELLENTWURF_ENTWURF_NAOVIEW_ROBOTERANZEIGE_BEINANZEIGE_BEINZEICHNER_H
#define NAOSIMULATIONMODELLENTWURF_ENTWURF_NAOVIEW_ROBOTERANZEIGE_BEINANZEIGE_BEINZEICHNER_H

/************************************************************
 BeinZeichner class header
 ************************************************************/

//#include "NaoSimulation/Entwurf/NaoView/Roboteranzeige/Beinanzeige/Pkg_Beinanzeige.h"
#include "../Koerperteilanzeige/KoerperteilZeichner.h"
#include "../../../../Modellierung/Roboterverwaltung/Bein/Bein.h"
#include "../../../../Modellierung/Roboterverwaltung/Bein/Fuss.h"
#include "../../../../Modellierung/Roboterverwaltung/Bein/Knie.h"
#include "../../../../Modellierung/Roboterverwaltung/Bein/Oberschenkel.h"
#include "../../../../Modellierung/Roboterverwaltung/Bein/Schienbein.h"
#include "../../../../Modellierung/Roboterverwaltung/Bein/Sprunggelenk.h"

/*
namespace NaoSimulation {
namespace Modellierung {
namespace Roboterverwaltung {
namespace Bein {
class Bein;
}
}
}
}
*/
namespace NaoSimulation {
namespace Entwurf {
namespace NaoView {
namespace Roboteranzeige {
namespace Beinanzeige {

/************************************************************/
/**
 * 
 */
class BeinZeichner {
public:
	static void zeichneBein(::NaoSimulation::Modellierung::Roboterverwaltung::Bein::Bein* bein);
};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Beinanzeige
} // of namespace Roboteranzeige
} // of namespace NaoView
} // of namespace Entwurf
} // of namespace NaoSimulation

/************************************************************
 End of BeinZeichner class header
 ************************************************************/

#endif
