// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define NaoSimulation_Entwurf_NaoView_Roboteranzeige_Beinanzeige_BeinZeichner_BODY

/************************************************************
 BeinZeichner class body
 ************************************************************/

// include associated header file
#include "BeinZeichner.h"

namespace NaoSimulation {
namespace Entwurf {
namespace NaoView {
namespace Roboteranzeige {
namespace Beinanzeige {

// static attributes (if any)

/**
 * 
 * @param bein 
 */
void BeinZeichner::zeichneBein(::NaoSimulation::Modellierung::Roboterverwaltung::Bein::Bein* bein) {
	// Zeichne Oberschenkel
	NaoSimulation::Entwurf::NaoView::Roboteranzeige::Koerperteilanzeige::KoerperteilZeichner::zeichneKoerperteil(*bein->getOberschenkel());
	// Zeichne Schienbein
	NaoSimulation::Entwurf::NaoView::Roboteranzeige::Koerperteilanzeige::KoerperteilZeichner::zeichneKoerperteil(*bein->getSchienbein());
	// Zeichne Fuss
	NaoSimulation::Entwurf::NaoView::Roboteranzeige::Koerperteilanzeige::KoerperteilZeichner::zeichneKoerperteil(*bein->getFuss());
}

} // of namespace Beinanzeige
} // of namespace Roboteranzeige
} // of namespace NaoView
} // of namespace Entwurf
} // of namespace NaoSimulation

/************************************************************
 End of BeinZeichner class body
 ************************************************************/
