// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef NAOSIMULATIONMODELLENTWURF_ENTWURF_NAOVIEW_ROBOTERANZEIGE_ARMANZEIGE_ARMZEICHNER_H
#define NAOSIMULATIONMODELLENTWURF_ENTWURF_NAOVIEW_ROBOTERANZEIGE_ARMANZEIGE_ARMZEICHNER_H

/************************************************************
 ArmZeichner class header
 ************************************************************/

#include "NaoSimulation/Entwurf/NaoView/Roboteranzeige/Armanzeige/Pkg_Armanzeige.h"
#include "NaoSimulation/Entwurf/NaoView/Roboteranzeige/Koerperteilanzeige/KoerperteilZeichner.h"
#include "NaoSimulation/Modellierung/Roboterverwaltung/Arm/Arm.h"
#include "NaoSimulation/Modellierung/Roboterverwaltung/Arm/Oberarm.h"
#include "NaoSimulation/Modellierung/Roboterverwaltung/Arm/Unterarm.h"
#include "NaoSimulation/Modellierung/Roboterverwaltung/Arm/Hand.h"
#include "NaoSimulation/Modellierung/Roboterverwaltung/Arm/Ellenbogen.h"
#include "NaoSimulation/Modellierung/Roboterverwaltung/Arm/Handgelenk.h"

/*
namespace NaoSimulation {
namespace Modellierung {
namespace Roboterverwaltung {
namespace Arm {
class Arm;
}
}
}
}
*/
namespace NaoSimulation {
namespace Entwurf {
namespace NaoView {
namespace Roboteranzeige {
namespace Armanzeige {

/************************************************************/
/**
 * 
 */
class ArmZeichner {
public:
	static void zeichneArm(::NaoSimulation::Modellierung::Roboterverwaltung::Arm::Arm* arm);
};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Armanzeige
} // of namespace Roboteranzeige
} // of namespace NaoView
} // of namespace Entwurf
} // of namespace NaoSimulation

/************************************************************
 End of ArmZeichner class header
 ************************************************************/

#endif
