// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define NaoSimulation_Entwurf_NaoView_Roboteranzeige_Armanzeige_ArmZeichner_BODY

/************************************************************
 ArmZeichner class body
 ************************************************************/

// include associated header file
#include "NaoSimulation/Entwurf/NaoView/Roboteranzeige/Armanzeige/ArmZeichner.h"

// Derived includes directives
#include "NaoSimulation/Modellierung/Roboterverwaltung/Arm/Arm.h"

namespace NaoSimulation {
namespace Entwurf {
namespace NaoView {
namespace Roboteranzeige {
namespace Armanzeige {


void ArmZeichner::zeichneArm(::NaoSimulation::Modellierung::Roboterverwaltung::Arm::Arm* arm) {
	// Zeichne Oberarm
	NaoSimulation::Entwurf::NaoView::Roboteranzeige::Koerperteilanzeige::KoerperteilZeichner::zeichneKoerperteil(*arm->getOberarm());
	// Zeichne Unterarm
	NaoSimulation::Entwurf::NaoView::Roboteranzeige::Koerperteilanzeige::KoerperteilZeichner::zeichneKoerperteil(*arm->getUnterarm());
	// Zeichne Hand
	NaoSimulation::Entwurf::NaoView::Roboteranzeige::Koerperteilanzeige::KoerperteilZeichner::zeichneKoerperteil(*arm->getHand());
}

} // of namespace Armanzeige
} // of namespace Roboteranzeige
} // of namespace NaoView
} // of namespace Entwurf
} // of namespace NaoSimulation

/************************************************************
 End of ArmZeichner class body
 ************************************************************/
