// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef NAOSIMULATION_MODELLIERUNG_ROBOTERVERWALTUNG_ARM_ARM_H
#define NAOSIMULATION_MODELLIERUNG_ROBOTERVERWALTUNG_ARM_ARM_H

/************************************************************
 Arm class header
 ************************************************************/

//#include "NaoSimulation/Modellierung/Roboterverwaltung/Arm/Pkg_Arm.h"

#include "Oberarm.h"
#include "Unterarm.h"
#include "Hand.h"
#include "Ellenbogen.h"
#include "Handgelenk.h"

/*
namespace NaoSimulation {
namespace Modellierung {
namespace Roboterverwaltung {
namespace Arm {
class Ellenbogen;
}
}
}
}
namespace NaoSimulation {
namespace Modellierung {
namespace Roboterverwaltung {
namespace Arm {
class Hand;
}
}
}
}
namespace NaoSimulation {
namespace Modellierung {
namespace Roboterverwaltung {
namespace Arm {
class Handgelenk;
}
}
}
}
namespace NaoSimulation {
namespace Modellierung {
namespace Roboterverwaltung {
namespace Arm {
class Oberarm;
}
}
}
}
namespace NaoSimulation {
namespace Modellierung {
namespace Roboterverwaltung {
namespace Arm {
class Unterarm;
}
}
}
}*/

namespace NaoSimulation {
namespace Modellierung {
namespace Roboterverwaltung {
namespace Arm {

/************************************************************/
/**
 * 
 */
class Arm : public NaoSimulation::Entwurf::NaoModel::BewegungsManagement::BewegbaresObjekt {
public:

	// Copy-Konstruktor
	Arm(Arm& arm) :
		oberarm(new Oberarm(*arm.getOberarm())),
		unterarm(new Unterarm(*arm.getUnterarm())),
		hand(new Hand(*arm.getHand())),
		handgelenk(new Handgelenk(*arm.getHandgelenk())),
		ellenbogen(new Ellenbogen(*arm.getEllenbogen())) {}
		

	// Konstruktor
	Arm(Oberarm* oberarm, Ellenbogen* ellenbogen, Unterarm* unterarm, Handgelenk* handgelenk, Hand* hand) : 
		oberarm(oberarm), ellenbogen(ellenbogen), unterarm(unterarm), handgelenk(handgelenk), hand(hand) {}

	// Destruktor
	~Arm();

	static Arm* erzeugeLinkenArm(
		Oberarm *oberarm,
		Ellenbogen *ellenbogen,
		Unterarm *unterarm,
		Handgelenk *handgelenk,
		Hand *hand,
		NaoSimulation::Entwurf::NaoModel::ODE::dWorldID welt
	);

	static Arm* erzeugeRechtenArm(
		Oberarm *oberarm,
		Ellenbogen *ellenbogen,
		Unterarm *unterarm,
		Handgelenk *handgelenk,
		Hand *hand,
		NaoSimulation::Entwurf::NaoModel::ODE::dWorldID welt
	);

	Oberarm* getOberarm();

	Ellenbogen* getEllenbogen();

	Unterarm* getUnterarm();

	Handgelenk* getHandgelenk();

	Hand* getHand();

	// ueberschreibe die Std-Implementierung fuer bewegbare Objekte
	bool inBewegung() override;

private:

	/**
	 * 
	 */
	Oberarm *oberarm;

	/**
	 * 
	 */
	Ellenbogen *ellenbogen;

	/**
	 * 
	 */
	Unterarm *unterarm;

	/**
	 * 
	 */
	Hand *hand;

	/**
	 * 
	 */
	Handgelenk *handgelenk;
};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Arm
} // of namespace Roboterverwaltung
} // of namespace Modellierung
} // of namespace NaoSimulation

/************************************************************
 End of Arm class header
 ************************************************************/

#endif
