// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef NAOSIMULATION_MODELLIERUNG_ROBOTERVERWALTUNG_ARM_BEWEGE_ARMGELENK_H
#define NAOSIMULATION_MODELLIERUNG_ROBOTERVERWALTUNG_ARM_BEWEGE_ARMGELENK_H

/************************************************************
 bewege_Armgelenk class header
 ************************************************************/

#include "NaoSimulation/Modellierung/Roboterverwaltung/Arm/Pkg_Arm.h"

#include "NaoSimulation/Modellierung/Roboterverwaltung/bewege_Gelenk.h"

namespace NaoSimulation {
namespace Modellierung {
namespace Roboterverwaltung {
namespace Arm {

/************************************************************/
/**
 * 
 */
class bewege_Armgelenk: public ::NaoSimulation::Modellierung::Roboterverwaltung::bewege_Gelenk {

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Arm
} // of namespace Roboterverwaltung
} // of namespace Modellierung
} // of namespace NaoSimulation

/************************************************************
 End of bewege_Armgelenk class header
 ************************************************************/

#endif
