// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef NAOSIMULATION_MODELLIERUNG_ROBOTERVERWALTUNG_ARM_BEWEGE_HAND_H
#define NAOSIMULATION_MODELLIERUNG_ROBOTERVERWALTUNG_ARM_BEWEGE_HAND_H

/************************************************************
 bewege_Hand class header
 ************************************************************/

#include "NaoSimulation/Modellierung/Roboterverwaltung/Arm/Pkg_Arm.h"

#include "NaoSimulation/Modellierung/Roboterverwaltung/Arm/bewege_Armgelenk.h"

namespace NaoSimulation {
namespace Modellierung {
namespace Roboterverwaltung {
namespace Arm {

/************************************************************/
/**
 * 
 */
class bewege_Hand {

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Arm
} // of namespace Roboterverwaltung
} // of namespace Modellierung
} // of namespace NaoSimulation

/************************************************************
 End of bewege_Hand class header
 ************************************************************/

#endif
