// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef NAOSIMULATION_MODELLIERUNG_ROBOTERVERWALTUNG_ARM_GIERE_HANDGELENK_H
#define NAOSIMULATION_MODELLIERUNG_ROBOTERVERWALTUNG_ARM_GIERE_HANDGELENK_H

/************************************************************
 giere_Handgelenk class header
 ************************************************************/

#include "NaoSimulation/Modellierung/Roboterverwaltung/Arm/Pkg_Arm.h"

#include "NaoSimulation/Modellierung/Roboterverwaltung/Arm/bewege_Armgelenk.h"

namespace NaoSimulation {
namespace Modellierung {
namespace Roboterverwaltung {
namespace Arm {

/************************************************************/
/**
 * 
 */
class giere_Handgelenk {

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Arm
} // of namespace Roboterverwaltung
} // of namespace Modellierung
} // of namespace NaoSimulation

/************************************************************
 End of giere_Handgelenk class header
 ************************************************************/

#endif
