// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define NaoSimulation_Modellierung_Roboterverwaltung_Arm_Hand_BODY

/************************************************************
 Hand class body
 ************************************************************/

// include associated header file
#include "Hand.h"

// Derived includes directives

namespace NaoSimulation {
namespace Modellierung {
namespace Roboterverwaltung {
namespace Arm {

// static attributes (if any)

Hand* Hand::erzeugeLinkeHand(NaoSimulation::Entwurf::NaoModel::ODE::dWorldID welt) {
    Hand* hand = new Hand();
    hand->setHoehe(linkeHandParams.hoehe);
    hand->setRadius(linkeHandParams.radius);
    hand->setOdeKoerperteil(NaoSimulation::Entwurf::NaoModel::ODE::erzeugeODEBody(
        linkeHandParams.masse,
        linkeHandParams.position,
        linkeHandParams.ausrichtung,
        linkeHandParams.radius,
        linkeHandParams.hoehe,
        welt
    ));

    return hand;
}

Hand* Hand::erzeugeRechteHand(NaoSimulation::Entwurf::NaoModel::ODE::dWorldID welt) {
    Hand* hand = new Hand();
    hand->hoehe             = rechteHandParams.hoehe;
    hand->radius            = rechteHandParams.radius;
    hand->setOdeKoerperteil(NaoSimulation::Entwurf::NaoModel::ODE::erzeugeODEBody(
        rechteHandParams.masse,
        rechteHandParams.position,
        rechteHandParams.ausrichtung,
        rechteHandParams.radius,
        rechteHandParams.hoehe,
        welt
    ));

    return hand;
}

} // of namespace Arm
} // of namespace Roboterverwaltung
} // of namespace Modellierung
} // of namespace NaoSimulation

/************************************************************
 End of Hand class body
 ************************************************************/
