// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef NAOSIMULATION_MODELLIERUNG_ROBOTERVERWALTUNG_ARM_HAND_H
#define NAOSIMULATION_MODELLIERUNG_ROBOTERVERWALTUNG_ARM_HAND_H

/************************************************************
 Hand class header
 ************************************************************/

//#include "NaoSimulation/Modellierung/Roboterverwaltung/Arm/Pkg_Arm.h"


#include "../../../Entwurf/NaoModel/Koerperteile/Koerperteil.h"

#include "../../Params/RoboterParamSettings.h"

namespace NaoSimulation {
namespace Modellierung {
namespace Roboterverwaltung {
namespace Arm {

/************************************************************/
/**
 * 
 */
class Hand: public ::NaoSimulation::Entwurf::NaoModel::Koerperteile::Koerperteil {
public:
	Hand() : Koerperteil() {}
	/**
	 * 
	 * @return result 
	 */
	static Hand* erzeugeLinkeHand(NaoSimulation::Entwurf::NaoModel::ODE::dWorldID welt);

	static Hand* erzeugeRechteHand(NaoSimulation::Entwurf::NaoModel::ODE::dWorldID welt);
};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Arm
} // of namespace Roboterverwaltung
} // of namespace Modellierung
} // of namespace NaoSimulation

/************************************************************
 End of Hand class header
 ************************************************************/

#endif
