// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define NaoSimulation_Modellierung_Roboterverwaltung_Arm_Handgelenk_BODY

/************************************************************
 Handgelenk class body
 ************************************************************/

// include associated header file
#include "Handgelenk.h"


namespace NaoSimulation {
namespace Modellierung {
namespace Roboterverwaltung {
namespace Arm {

Handgelenk* Handgelenk::erzeugeLinkesHandgelenk(
    Unterarm* unterarm,
    Hand* hand,
    NaoSimulation::Entwurf::NaoModel::ODE::dWorldID welt
) {
    Handgelenk* handgelenk = new Handgelenk(
        unterarm,
        hand,
        0.0,
        linkesHandgelenkGierenParams.minWinkel,
        linkesHandgelenkGierenParams.maxWinkel
    );

    handgelenk->setODEGelenk(NaoSimulation::Entwurf::NaoModel::ODE::erzeugeODEGelenk(
        linkesHandgelenkGierenParams.position,
        linkesHandgelenkGierenParams.ausrichtung,
        linkesHandgelenkGierenParams.maxGeschwindigkeit,
        handgelenk->getGierWinkelMax(),
        handgelenk->getGierWinkelMin(),
        welt,
        handgelenk->getUnterarm()->getOdeKoerperteil(),
        handgelenk->getHand()->getOdeKoerperteil()
    ));

    return handgelenk;
}

Handgelenk* Handgelenk::erzeugeRechtesHandgelenk(
    Unterarm* unterarm,
    Hand* hand,
    NaoSimulation::Entwurf::NaoModel::ODE::dWorldID welt
) {
    Handgelenk* handgelenk = new Handgelenk(
        unterarm,
        hand,
        0.0,
        rechtesHandgelenkGierenParams.minWinkel,
        rechtesHandgelenkGierenParams.maxWinkel
    );

    handgelenk->setODEGelenk(NaoSimulation::Entwurf::NaoModel::ODE::erzeugeODEGelenk(
        rechtesHandgelenkGierenParams.position,
        rechtesHandgelenkGierenParams.ausrichtung,
        rechtesHandgelenkGierenParams.maxGeschwindigkeit,
        handgelenk->getGierWinkelMax(),
        handgelenk->getGierWinkelMin(),
        welt,
        handgelenk->getUnterarm()->getOdeKoerperteil(),
        handgelenk->getHand()->getOdeKoerperteil()
    ));

    return handgelenk;
}

void Handgelenk::giereHandgelenk(::PrimitiveTypes::Real winkel) {
    NaoSimulation::Entwurf::NaoModel::ODE::bewegeGelenk(odeGelenk, winkel, &bewegtSich);
}

/**
 * 
 * @return result 
 */
::PrimitiveTypes::Real Handgelenk::getGierWinkel() {
	return fg.getWinkel();
}

/**
 * 
 * @return result 
 */
::PrimitiveTypes::Real Handgelenk::getGierWinkelMax() {
	return fg.getWinkelMax();
}

/**
 * 
 * @return result 
 */
::PrimitiveTypes::Real Handgelenk::getGierWinkelMin() {
	return fg.getWinkelMin();
}

Unterarm* Handgelenk::getUnterarm() {
    return this->unterarm;
}

Hand* Handgelenk::getHand() {
    return this->hand;
}

} // of namespace Arm
} // of namespace Roboterverwaltung
} // of namespace Modellierung
} // of namespace NaoSimulation

/************************************************************
 End of Handgelenk class body
 ************************************************************/
