// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define NaoSimulation_Modellierung_Roboterverwaltung_Arm_Oberarm_BODY

/************************************************************
 Oberarm class body
 ************************************************************/

// include associated header file
#include "Oberarm.h"

// Derived includes directives

namespace NaoSimulation {
namespace Modellierung {
namespace Roboterverwaltung {
namespace Arm {

Oberarm* Oberarm::erzeugeLinkenOberarm(NaoSimulation::Entwurf::NaoModel::ODE::dWorldID welt) {
    Oberarm* oberarm = new Oberarm();
    oberarm->setHoehe(linkerOberarmParams.hoehe);
    oberarm->setRadius(linkerOberarmParams.radius);
    oberarm->setOdeKoerperteil(NaoSimulation::Entwurf::NaoModel::ODE::erzeugeODEBody(
        linkerOberarmParams.masse,
        linkerOberarmParams.position,
        linkerOberarmParams.ausrichtung,
        linkerOberarmParams.radius,
        linkerOberarmParams.hoehe,
        welt
    ));

    return oberarm;
}

Oberarm* Oberarm::erzeugeRechtenOberarm(NaoSimulation::Entwurf::NaoModel::ODE::dWorldID welt) {
    Oberarm* oberarm = new Oberarm();
    oberarm->setHoehe(rechterOberarmParams.hoehe);
    oberarm->setRadius(rechterOberarmParams.radius);
    oberarm->setOdeKoerperteil(NaoSimulation::Entwurf::NaoModel::ODE::erzeugeODEBody(
        rechterOberarmParams.masse,
        rechterOberarmParams.position,
        rechterOberarmParams.ausrichtung,
        rechterOberarmParams.radius,
        rechterOberarmParams.hoehe,
        welt
    ));

    return oberarm;
}

} // of namespace Arm
} // of namespace Roboterverwaltung
} // of namespace Modellierung
} // of namespace NaoSimulation

/************************************************************
 End of Oberarm class body
 ************************************************************/
