// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef NAOSIMULATION_MODELLIERUNG_ROBOTERVERWALTUNG_ARM_OBERARM_H
#define NAOSIMULATION_MODELLIERUNG_ROBOTERVERWALTUNG_ARM_OBERARM_H

/************************************************************
 Oberarm class header
 ************************************************************/

//#include "NaoSimulation/Modellierung/Roboterverwaltung/Arm/Pkg_Arm.h"

#include "../../../Entwurf/NaoModel/Koerperteile/Koerperteil.h"

#include "../../Params/RoboterParamSettings.h"

namespace NaoSimulation {
namespace Modellierung {
namespace Roboterverwaltung {
namespace Arm {

/************************************************************/
/**
 * 
 */
class Oberarm: public ::NaoSimulation::Entwurf::NaoModel::Koerperteile::Koerperteil {
public:
	Oberarm() : Koerperteil() {}
	/**
	 * 
	 * @return result 
	 */
	static Oberarm* erzeugeLinkenOberarm(NaoSimulation::Entwurf::NaoModel::ODE::dWorldID welt);

	static Oberarm* erzeugeRechtenOberarm(NaoSimulation::Entwurf::NaoModel::ODE::dWorldID welt);
};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Arm
} // of namespace Roboterverwaltung
} // of namespace Modellierung
} // of namespace NaoSimulation

/************************************************************
 End of Oberarm class header
 ************************************************************/

#endif
