// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef NAOSIMULATION_MODELLIERUNG_ROBOTERVERWALTUNG_ARM_ROLLE ELLENBOGEN_H
#define NAOSIMULATION_MODELLIERUNG_ROBOTERVERWALTUNG_ARM_ROLLE ELLENBOGEN_H

/************************************************************
 rolle Ellenbogen class header
 ************************************************************/

#include "NaoSimulation/Modellierung/Roboterverwaltung/Arm/Pkg_Arm.h"

#include "NaoSimulation/Modellierung/Roboterverwaltung/Arm/bewege_Ellenbogen.h"

namespace NaoSimulation {
namespace Modellierung {
namespace Roboterverwaltung {
namespace Arm {

/************************************************************/
/**
 * 
 */
class rolle Ellenbogen {

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Arm
} // of namespace Roboterverwaltung
} // of namespace Modellierung
} // of namespace NaoSimulation

/************************************************************
 End of rolle Ellenbogen class header
 ************************************************************/

#endif
