// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef NAOSIMULATION_MODELLIERUNG_ROBOTERVERWALTUNG_ARM_UNTERARM_H
#define NAOSIMULATION_MODELLIERUNG_ROBOTERVERWALTUNG_ARM_UNTERARM_H

/************************************************************
 Unterarm class header
 ************************************************************/

//#include "NaoSimulation/Modellierung/Roboterverwaltung/Arm/Pkg_Arm.h"

#include "../../../Entwurf/NaoModel/Koerperteile/Koerperteil.h"

#include "../../Params/RoboterParamSettings.h"


namespace NaoSimulation {
namespace Modellierung {
namespace Roboterverwaltung {
namespace Arm {

/************************************************************/
/**
 * 
 */
class Unterarm: public ::NaoSimulation::Entwurf::NaoModel::Koerperteile::Koerperteil {
public:
	Unterarm() : Koerperteil() {}
	/**
	 * 
	 * @return result
	 */
	static Unterarm* erzeugeLinkenUnterarm(NaoSimulation::Entwurf::NaoModel::ODE::dWorldID welt);

	static Unterarm* erzeugeRechtenUnterarm(NaoSimulation::Entwurf::NaoModel::ODE::dWorldID welt);

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Arm
} // of namespace Roboterverwaltung
} // of namespace Modellierung
} // of namespace NaoSimulation

/************************************************************
 End of Unterarm class header
 ************************************************************/

#endif
