// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define NaoSimulation_Modellierung_Roboterverwaltung_Arm_Unterarm_BODY

/************************************************************
 Unterarm class body
 ************************************************************/

// include associated header file
#include "Unterarm.h"

// Derived includes directives

namespace NaoSimulation {
namespace Modellierung {
namespace Roboterverwaltung {
namespace Arm {

Unterarm* Unterarm::erzeugeLinkenUnterarm(NaoSimulation::Entwurf::NaoModel::ODE::dWorldID welt) {
    Unterarm* unterarm = new Unterarm();
    unterarm->setHoehe(linkerUnterarmParams.hoehe);
    unterarm->setRadius(linkerUnterarmParams.radius);
    unterarm->setOdeKoerperteil(NaoSimulation::Entwurf::NaoModel::ODE::erzeugeODEBody(
        linkerUnterarmParams.masse,
        linkerUnterarmParams.position,
        linkerUnterarmParams.ausrichtung,
        linkerUnterarmParams.radius,
        linkerUnterarmParams.hoehe,
        welt
    ));
    
    return unterarm;
}

Unterarm* Unterarm::erzeugeRechtenUnterarm(NaoSimulation::Entwurf::NaoModel::ODE::dWorldID welt) {
    Unterarm* unterarm = new Unterarm();
    unterarm->setHoehe(rechterUnterarmParams.hoehe);
    unterarm->setRadius(rechterUnterarmParams.radius);
    unterarm->setOdeKoerperteil(NaoSimulation::Entwurf::NaoModel::ODE::erzeugeODEBody(
        rechterUnterarmParams.masse,
        rechterUnterarmParams.position,
        rechterUnterarmParams.ausrichtung,
        rechterUnterarmParams.radius,
        rechterUnterarmParams.hoehe,
        welt
    ));

    return unterarm;
}

} // of namespace Arm
} // of namespace Roboterverwaltung
} // of namespace Modellierung
} // of namespace NaoSimulation

/************************************************************
 End of Unterarm class body
 ************************************************************/
