// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef NAOSIMULATIONMODELLENTWURF_ENTWURF_NAOCONTROLLER_COMMAND_COMMAND_H
#define NAOSIMULATIONMODELLENTWURF_ENTWURF_NAOCONTROLLER_COMMAND_COMMAND_H

/************************************************************
 Command class header
 ************************************************************/

#include "NaoSimulation/Entwurf/NaoController/Command/Pkg_Command.h"

namespace NaoSimulation {
namespace Entwurf {
namespace NaoController {
namespace Command {

/************************************************************/
/**
 * 
 */
class Command {
public:

	/**
	 * 
	 */
	virtual void execute() = 0;

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Command
} // of namespace NaoController
} // of namespace Entwurf
} // of namespace NaoSimulation

/************************************************************
 End of Command class header
 ************************************************************/

#endif
