// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef NAOSIMULATIONMODELLENTWURF_ENTWURF_NAOCONTROLLER_COMMAND_GELENKCOMMAND_H
#define NAOSIMULATIONMODELLENTWURF_ENTWURF_NAOCONTROLLER_COMMAND_GELENKCOMMAND_H

/************************************************************
 GelenkCommand class header
 ************************************************************/

#include "NaoSimulation/Entwurf/NaoController/Command/Pkg_Command.h"

#include "NaoSimulation/Entwurf/NaoController/Command/Command.h"
#include "PrimitiveTypes/Pkg_PrimitiveTypes.h"

namespace NaoSimulation {
namespace Entwurf {
namespace NaoController {
namespace Command {

/************************************************************/
/**
 * 
 */
class GelenkCommand: public Command {
public:

	/**
	 * 
	 * @param winkel 
	 */
	virtual void setzeParameter(::PrimitiveTypes::Real /*in*/winkel) = 0;

protected:

	/**
	 * 
	 */
	::PrimitiveTypes::Real winkel;

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Command
} // of namespace NaoController
} // of namespace Entwurf
} // of namespace NaoSimulation

/************************************************************
 End of GelenkCommand class header
 ************************************************************/

#endif
