// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef NAOSIMULATIONMODELLENTWURF_ENTWURF_NAOCONTROLLER_COMMAND_ARMCOMMAND_LELLENBOGENGIERENCC_H
#define NAOSIMULATIONMODELLENTWURF_ENTWURF_NAOCONTROLLER_COMMAND_ARMCOMMAND_LELLENBOGENGIERENCC_H

/************************************************************
 LEllenbogenGierenCC class header
 ************************************************************/

#include "NaoSimulation/Entwurf/NaoController/Command/ArmCommand/Pkg_ArmCommand.h"

#include "NaoSimulation/Entwurf/NaoController/Command/GelenkCommand.h"
#include "NaoSimulation/Modellierung/Roboterverwaltung/Arm/Ellenbogen.h"
#include "PrimitiveTypes/Pkg_PrimitiveTypes.h"

namespace NaoSimulation {
namespace Entwurf {
namespace NaoController {
namespace Command {
namespace ArmCommand {

/************************************************************/
/**
 * 
 */
class LEllenbogenGierenCC: public ::NaoSimulation::Entwurf::NaoController::Command::GelenkCommand {
private:
	::NaoSimulation::Modellierung::Roboterverwaltung::Arm::Ellenbogen* ellenbogen;

	::PrimitiveTypes::Real winkel;
public:
	LEllenbogenGierenCC(::NaoSimulation::Modellierung::Roboterverwaltung::Arm::Ellenbogen* ellenbogen):
		ellenbogen(ellenbogen),
		winkel(0.0) {}

	void execute();

	void setzeParameter(::PrimitiveTypes::Real winkel);
};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace ArmCommand
} // of namespace Command
} // of namespace NaoController
} // of namespace Entwurf
} // of namespace NaoSimulation

/************************************************************
 End of LEllenbogenGierenCC class header
 ************************************************************/

#endif
