// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define NaoSimulation_Entwurf_NaoController_Command_ArmCommand_LHandgelenkGierenCC_BODY

/************************************************************
 LHandgelenkGierenCC class body
 ************************************************************/

// include associated header file
#include "NaoSimulation/Entwurf/NaoController/Command/ArmCommand/LHandgelenkGierenCC.h"

// Derived includes directives

namespace NaoSimulation {
namespace Entwurf {
namespace NaoController {
namespace Command {
namespace ArmCommand {

void LHandgelenkGierenCC::execute() {
    handgelenk->giereHandgelenk(winkel);
}

void LHandgelenkGierenCC::setzeParameter(::PrimitiveTypes::Real winkel) {
    this->winkel = winkel;
}

} // of namespace ArmCommand
} // of namespace Command
} // of namespace NaoController
} // of namespace Entwurf
} // of namespace NaoSimulation

/************************************************************
 End of LHandgelenkGierenCC class body
 ************************************************************/
