// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef NAOSIMULATIONMODELLENTWURF_ENTWURF_NAOCONTROLLER_COMMAND_ARMCOMMAND_RHANDGELENKGIERENCC_H
#define NAOSIMULATIONMODELLENTWURF_ENTWURF_NAOCONTROLLER_COMMAND_ARMCOMMAND_RHANDGELENKGIERENCC_H

/************************************************************
 RHandgelenkGierenCC class header
 ************************************************************/

#include "NaoSimulation/Entwurf/NaoController/Command/ArmCommand/Pkg_ArmCommand.h"

#include "NaoSimulation/Entwurf/NaoController/Command/GelenkCommand.h"
#include "NaoSimulation/Modellierung/Roboterverwaltung/Arm/Handgelenk.h"
#include "PrimitiveTypes/Pkg_PrimitiveTypes.h"

namespace NaoSimulation {
namespace Entwurf {
namespace NaoController {
namespace Command {
namespace ArmCommand {

/************************************************************/
/**
 * 
 */
class RHandgelenkGierenCC: public ::NaoSimulation::Entwurf::NaoController::Command::GelenkCommand {
private:
	::NaoSimulation::Modellierung::Roboterverwaltung::Arm::Handgelenk* handgelenk;

	::PrimitiveTypes::Real winkel;
public:
	RHandgelenkGierenCC(::NaoSimulation::Modellierung::Roboterverwaltung::Arm::Handgelenk* handgelenk):
		handgelenk(handgelenk), winkel(0.0) {}

	void execute();

	void setzeParameter(::PrimitiveTypes::Real winkel);
};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace ArmCommand
} // of namespace Command
} // of namespace NaoController
} // of namespace Entwurf
} // of namespace NaoSimulation

/************************************************************
 End of RHandgelenkGierenCC class header
 ************************************************************/

#endif
