// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define NaoSimulation_Entwurf_NaoController_Command_ArmCommand_RHandOeffnenCC_BODY

/************************************************************
 RHandOeffnenCC class body
 ************************************************************/

// include associated header file
#include "NaoSimulation/Entwurf/NaoController/Command/ArmCommand/RHandOeffnenCC.h"

// Derived includes directives

namespace NaoSimulation {
namespace Entwurf {
namespace NaoController {
namespace Command {
namespace ArmCommand {

void RHandOeffnenCC::execute() {
    //hand->bewegeHand();
}

void RHandOeffnenCC::setzeParameter(::PrimitiveTypes::Real winkel) {
    this->winkel = winkel;
}

} // of namespace ArmCommand
} // of namespace Command
} // of namespace NaoController
} // of namespace Entwurf
} // of namespace NaoSimulation

/************************************************************
 End of RHandOeffnenCC class body
 ************************************************************/
