// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define NaoSimulation_Entwurf_NaoController_Command_ArmCommand_RHandschliessenCC_BODY

/************************************************************
 RHandschliessenCC class body
 ************************************************************/

// include associated header file
#include "NaoSimulation/Entwurf/NaoController/Command/ArmCommand/RHandschliessenCC.h"

// Derived includes directives

namespace NaoSimulation {
namespace Entwurf {
namespace NaoController {
namespace Command {
namespace ArmCommand {

void RHandschliessenCC::execute() {
    //hand->bewegeHand();
}

void RHandschliessenCC::setzeParameter(::PrimitiveTypes::Real winkel) {
    this->winkel = winkel;
}

} // of namespace ArmCommand
} // of namespace Command
} // of namespace NaoController
} // of namespace Entwurf
} // of namespace NaoSimulation

/************************************************************
 End of RHandschliessenCC class body
 ************************************************************/
