// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef NAOSIMULATIONMODELLENTWURF_ENTWURF_NAOCONTROLLER_COMMAND_ARMCOMMAND_RHANDOEFFNENCC_H
#define NAOSIMULATIONMODELLENTWURF_ENTWURF_NAOCONTROLLER_COMMAND_ARMCOMMAND_RHANDOEFFNENCC_H

/************************************************************
 RHandOeffnenCC class header
 ************************************************************/

#include "NaoSimulation/Entwurf/NaoController/Command/ArmCommand/Pkg_ArmCommand.h"

#include "NaoSimulation/Entwurf/NaoController/Command/GelenkCommand.h"
#include "NaoSimulation/Modellierung/Roboterverwaltung/Arm/Hand.h"
#include "PrimitiveTypes/Pkg_PrimitiveTypes.h"

namespace NaoSimulation {
namespace Entwurf {
namespace NaoController {
namespace Command {
namespace ArmCommand {

/************************************************************/
/**
 * 
 */
class RHandOeffnenCC: public ::NaoSimulation::Entwurf::NaoController::Command::GelenkCommand {
private:
	::NaoSimulation::Modellierung::Roboterverwaltung::Arm::Hand* hand;

	::PrimitiveTypes::Real winkel;
public:
	RHandOeffnenCC(::NaoSimulation::Modellierung::Roboterverwaltung::Arm::Hand* hand):
		hand(hand), winkel(0.0) {}

	void execute();

	void setzeParameter(::PrimitiveTypes::Real winkel);

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace ArmCommand
} // of namespace Command
} // of namespace NaoController
} // of namespace Entwurf
} // of namespace NaoSimulation

/************************************************************
 End of RHandOeffnenCC class header
 ************************************************************/

#endif
