// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef NAOSIMULATION_MODELLIERUNG_ROBOTERVERWALTUNG_RUMPF_BECKEN_H
#define NAOSIMULATION_MODELLIERUNG_ROBOTERVERWALTUNG_RUMPF_BECKEN_H

/************************************************************
 Becken class header
 ************************************************************/

//#include "NaoSimulation/Modellierung/Roboterverwaltung/Rumpf/Pkg_Rumpf.h"

#include "../../../Entwurf/NaoModel/Koerperteile/Koerperteil.h"
#include "../../Params/RoboterParamSettings.h"

namespace NaoSimulation {
namespace Modellierung {
namespace Roboterverwaltung {
namespace Rumpf {

/************************************************************/
/**
 * 
 */
class Becken: public ::NaoSimulation::Entwurf::NaoModel::Koerperteile::Koerperteil {
public:
	Becken() : Koerperteil() {}
	/**
	 * 
	 * @return result 
	 */
	static Becken* erzeugeLinkesBecken(NaoSimulation::Entwurf::NaoModel::ODE::dWorldID welt);

	static Becken* erzeugeRechtesBecken(NaoSimulation::Entwurf::NaoModel::ODE::dWorldID welt);
};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Rumpf
} // of namespace Roboterverwaltung
} // of namespace Modellierung
} // of namespace NaoSimulation

/************************************************************
 End of Becken class header
 ************************************************************/

#endif
