// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define NaoSimulation_Modellierung_Roboterverwaltung_Rumpf_Beckengelenk_BODY

/************************************************************
 Beckengelenk class body
 ************************************************************/

// include associated header file
#include "Beckengelenk.h"


namespace NaoSimulation {
namespace Modellierung {
namespace Roboterverwaltung {
namespace Rumpf {


Beckengelenk* Beckengelenk::erzeugeBeckengelenk(Torso* torso, Becken* linkesBecken, Becken* rechtesBecken, NaoSimulation::Entwurf::NaoModel::ODE::dWorldID welt) {
	Beckengelenk* beckengelenk = new Beckengelenk(torso, linkesBecken, rechtesBecken);

    return beckengelenk;
}

} // of namespace Rumpf
} // of namespace Roboterverwaltung
} // of namespace Modellierung
} // of namespace NaoSimulation

/************************************************************
 End of Beckengelenk class body
 ************************************************************/
