// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef NAOSIMULATION_MODELLIERUNG_ROBOTERVERWALTUNG_RUMPF_BECKENGELENK_H
#define NAOSIMULATION_MODELLIERUNG_ROBOTERVERWALTUNG_RUMPF_BECKENGELENK_H

/************************************************************
 Beckengelenk class header
 ************************************************************/

//#include "NaoSimulation/Modellierung/Roboterverwaltung/Rumpf/Pkg_Rumpf.h"

#include "Torso.h"
#include "Becken.h"

/*
namespace NaoSimulation {
namespace Modellierung {
namespace Roboterverwaltung {
namespace Rumpf {
class Becken;
}
}
}
}
namespace NaoSimulation {
namespace Modellierung {
namespace Roboterverwaltung {
namespace Rumpf {
class Torso;
}
}
}
}
*/
namespace NaoSimulation {
namespace Modellierung {
namespace Roboterverwaltung {
namespace Rumpf {

/************************************************************/
/**
 * 
 */
class Beckengelenk {
public:

	Beckengelenk(Torso* torso, Becken* linkesBecken, Becken* rechtesBecken):
		torso(torso), becken {linkesBecken, rechtesBecken} {}

	/**
	 * 
	 * @return result 
	 * @param torso 
	 * @param becken 
	 */
	static Beckengelenk* erzeugeBeckengelenk(Torso* torso,
			Becken* linkesBecken, Becken* rechtesBecken,
			NaoSimulation::Entwurf::NaoModel::ODE::dWorldID welt);

private:

	/**
	 * 
	 */
	Torso *torso;

	/**
	 * 
	 */
	Becken* becken[2];
};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Rumpf
} // of namespace Roboterverwaltung
} // of namespace Modellierung
} // of namespace NaoSimulation

/************************************************************
 End of Beckengelenk class header
 ************************************************************/

#endif
