// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef NAOSIMULATION_MODELLIERUNG_ROBOTERVERWALTUNG_RUMPF_BEWEGE SCHULTERGELENK_H
#define NAOSIMULATION_MODELLIERUNG_ROBOTERVERWALTUNG_RUMPF_BEWEGE SCHULTERGELENK_H

/************************************************************
 bewege Schultergelenk class header
 ************************************************************/

#include "NaoSimulation/Modellierung/Roboterverwaltung/Rumpf/Pkg_Rumpf.h"

#include "NaoSimulation/Modellierung/Roboterverwaltung/Rumpf/bewege_Rumpfgelenk.h"

namespace NaoSimulation {
namespace Modellierung {
namespace Roboterverwaltung {
namespace Rumpf {

/************************************************************/
/**
 * 
 */
class bewege Schultergelenk {

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Rumpf
} // of namespace Roboterverwaltung
} // of namespace Modellierung
} // of namespace NaoSimulation

/************************************************************
 End of bewege Schultergelenk class header
 ************************************************************/

#endif
