// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef NAOSIMULATION_MODELLIERUNG_ROBOTERVERWALTUNG_RUMPF_BEWEGE_RUMPFGELENK_H
#define NAOSIMULATION_MODELLIERUNG_ROBOTERVERWALTUNG_RUMPF_BEWEGE_RUMPFGELENK_H

/************************************************************
 bewege_Rumpfgelenk class header
 ************************************************************/

#include "NaoSimulation/Modellierung/Roboterverwaltung/Rumpf/Pkg_Rumpf.h"

#include "NaoSimulation/Modellierung/Roboterverwaltung/bewege_Gelenk.h"

namespace NaoSimulation {
namespace Modellierung {
namespace Roboterverwaltung {
namespace Rumpf {

/************************************************************/
/**
 * 
 */
class bewege_Rumpfgelenk: public ::NaoSimulation::Modellierung::Roboterverwaltung::bewege_Gelenk {

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Rumpf
} // of namespace Roboterverwaltung
} // of namespace Modellierung
} // of namespace NaoSimulation

/************************************************************
 End of bewege_Rumpfgelenk class header
 ************************************************************/

#endif
