// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef NAOSIMULATION_MODELLIERUNG_ROBOTERVERWALTUNG_RUMPF_GIER_NICKE_BECKENGELENK_H
#define NAOSIMULATION_MODELLIERUNG_ROBOTERVERWALTUNG_RUMPF_GIER_NICKE_BECKENGELENK_H

/************************************************************
 gier_nicke_Beckengelenk class header
 ************************************************************/

#include "NaoSimulation/Modellierung/Roboterverwaltung/Rumpf/Pkg_Rumpf.h"

#include "NaoSimulation/Modellierung/Roboterverwaltung/Rumpf/bewege Beckengelenk.h"

namespace NaoSimulation {
namespace Modellierung {
namespace Roboterverwaltung {
namespace Rumpf {

/************************************************************/
/**
 * 
 */
class gier_nicke_Beckengelenk {

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Rumpf
} // of namespace Roboterverwaltung
} // of namespace Modellierung
} // of namespace NaoSimulation

/************************************************************
 End of gier_nicke_Beckengelenk class header
 ************************************************************/

#endif
