// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef NAOSIMULATION_MODELLIERUNG_ROBOTERVERWALTUNG_RUMPF_HUEFTGELENK_H
#define NAOSIMULATION_MODELLIERUNG_ROBOTERVERWALTUNG_RUMPF_HUEFTGELENK_H

/************************************************************
 Hueftgelenk class header
 ************************************************************/

//#include "NaoSimulation/Modellierung/Roboterverwaltung/Rumpf/Pkg_Rumpf.h"

#include "Becken.h"
#include "../Bein/Oberschenkel.h"

/*
namespace NaoSimulation {
namespace Modellierung {
namespace Roboterverwaltung {
namespace Bein {
class Oberschenkel;
}
}
}
}
namespace NaoSimulation {
namespace Modellierung {
namespace Roboterverwaltung {
namespace Rumpf {
class Becken;
}
}
}
}
*/
namespace NaoSimulation {
namespace Modellierung {
namespace Roboterverwaltung {
namespace Rumpf {

/************************************************************/
/**
 * 
 */
class Hueftgelenk {
public:
	Hueftgelenk(Becken* becken, Bein::Oberschenkel* oberschenkel) : becken(becken), oberschenkel(oberschenkel) {}


	static Hueftgelenk* erzeugeRechtesHueftgelenk(Becken *becken,
			::NaoSimulation::Modellierung::Roboterverwaltung::Bein::Oberschenkel *oberschenkel, NaoSimulation::Entwurf::NaoModel::ODE::dWorldID welt);

	static Hueftgelenk* erzeugeLinkesHueftgelenk(Becken *becken,
			::NaoSimulation::Modellierung::Roboterverwaltung::Bein::Oberschenkel *oberschenkel, NaoSimulation::Entwurf::NaoModel::ODE::dWorldID welt);

private:

	/**
	 * 
	 */
	Becken* becken;

	/**
	 * 
	 */
	::NaoSimulation::Modellierung::Roboterverwaltung::Bein::Oberschenkel* oberschenkel;
};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Rumpf
} // of namespace Roboterverwaltung
} // of namespace Modellierung
} // of namespace NaoSimulation

/************************************************************
 End of Hueftgelenk class header
 ************************************************************/

#endif
