// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define NaoSimulation_Modellierung_Roboterverwaltung_Rumpf_Hueftgelenk_BODY

/************************************************************
 Hueftgelenk class body
 ************************************************************/

// include associated header file
#include "Hueftgelenk.h"

namespace NaoSimulation {
namespace Modellierung {
namespace Roboterverwaltung {
namespace Rumpf {

Hueftgelenk* Hueftgelenk::erzeugeRechtesHueftgelenk(Becken* becken,
		::NaoSimulation::Modellierung::Roboterverwaltung::Bein::Oberschenkel *oberschenkel, NaoSimulation::Entwurf::NaoModel::ODE::dWorldID welt) {
	Hueftgelenk* hueftgelenk = new Hueftgelenk(becken, oberschenkel);

    return hueftgelenk;
}

/**
 * 
 * @return result 
 * @param becken 
 * @param oberschenkel 
 */
Hueftgelenk* Hueftgelenk::erzeugeLinkesHueftgelenk(Becken* becken,
		::NaoSimulation::Modellierung::Roboterverwaltung::Bein::Oberschenkel *oberschenkel, NaoSimulation::Entwurf::NaoModel::ODE::dWorldID welt) {
	Hueftgelenk* hueftgelenk = new Hueftgelenk(becken, oberschenkel);

    return hueftgelenk;
}

} // of namespace Rumpf
} // of namespace Roboterverwaltung
} // of namespace Modellierung
} // of namespace NaoSimulation

/************************************************************
 End of Hueftgelenk class body
 ************************************************************/
