// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef NAOSIMULATION_MODELLIERUNG_ROBOTERVERWALTUNG_RUMPF_RUMPF_H
#define NAOSIMULATION_MODELLIERUNG_ROBOTERVERWALTUNG_RUMPF_RUMPF_H

/************************************************************
 Rumpf class header
 ************************************************************/

//#include "NaoSimulation/Modellierung/Roboterverwaltung/Rumpf/Pkg_Rumpf.h"

#include "../Arm/Arm.h"
#include "../Arm/Oberarm.h"
#include "../Bein/Bein.h"
#include "../Bein/Oberschenkel.h"

#include "Torso.h"
#include "Becken.h"
#include "Beckengelenk.h"
#include "Hueftgelenk.h"
#include "Schulter.h"

/*
namespace NaoSimulation {
namespace Modellierung {
namespace Roboterverwaltung {
namespace Arm {
class Arm;
}
}
}
}
namespace NaoSimulation {
namespace Modellierung {
namespace Roboterverwaltung {
namespace Bein {
class Bein;
}
}
}
}
namespace NaoSimulation {
namespace Modellierung {
namespace Roboterverwaltung {
namespace Rumpf {
class Becken;
}
}
}
}
namespace NaoSimulation {
namespace Modellierung {
namespace Roboterverwaltung {
namespace Rumpf {
class Beckengelenk;
}
}
}
}
namespace NaoSimulation {
namespace Modellierung {
namespace Roboterverwaltung {
namespace Rumpf {
class Hueftgelenk;
}
}
}
}
namespace NaoSimulation {
namespace Modellierung {
namespace Roboterverwaltung {
namespace Rumpf {
class Schulter;
}
}
}
}
namespace NaoSimulation {
namespace Modellierung {
namespace Roboterverwaltung {
namespace Rumpf {
class Torso;
}
}
}
}
*/
namespace NaoSimulation {
namespace Modellierung {
namespace Roboterverwaltung {
namespace Rumpf {

/************************************************************/
/**
 * 
 */
class Rumpf {
private:
	/**
	 * 
	 */
	Torso *torso;

	/**
	 * 
	 */
	Beckengelenk *beckengelenk;

	/**
	 * 
	 */
	Becken *becken[2];

	/**
	 * 
	 */
	Hueftgelenk *hueftgelenk[2];

	/**
	 * 
	 */
	Schulter *schulter[2];
public:

	Rumpf(
		Torso* torso, Beckengelenk* beckengelenk,
		Becken* linkesBecken, Becken* rechtesBecken,
		Hueftgelenk* linkesHueftgelenk, Hueftgelenk* rechtesHueftgelenk,
		Schulter* linkesSchulter, Schulter* rechteSchulter):
		torso(torso), beckengelenk(beckengelenk), becken {linkesBecken, rechtesBecken}, hueftgelenk {linkesHueftgelenk, rechtesHueftgelenk},
		schulter {linkesSchulter, rechteSchulter} {}

	static Rumpf* erzeugeRumpf(
			::NaoSimulation::Modellierung::Roboterverwaltung::Arm::Arm *rechterArm,
			::NaoSimulation::Modellierung::Roboterverwaltung::Arm::Arm *linkerArm,
			::NaoSimulation::Modellierung::Roboterverwaltung::Bein::Bein *rechtesBein,
			::NaoSimulation::Modellierung::Roboterverwaltung::Bein::Bein *linkesBein,
			NaoSimulation::Entwurf::NaoModel::ODE::dWorldID welt);
	
	Torso* getTorso();

	Beckengelenk* getBeckengelenk();

	Becken* getLinkesBecken();

	Becken* getRechtesBecken();

	Hueftgelenk* getLinkesHueftgelenk();

	Hueftgelenk* getRechtesHueftgelenk();

	Schulter* getLinkeSchulter();

	Schulter* getRechteSchulter();
};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Rumpf
} // of namespace Roboterverwaltung
} // of namespace Modellierung
} // of namespace NaoSimulation

/************************************************************
 End of Rumpf class header
 ************************************************************/

#endif
