// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#include "Hueftgelenk.h"
#include "Schulter.h"
#include <ode/common.h>
#define NaoSimulation_Modellierung_Roboterverwaltung_Rumpf_Rumpf_BODY

/************************************************************
 Rumpf class body
 ************************************************************/

// include associated header file
#include "Rumpf.h"

namespace NaoSimulation {
namespace Modellierung {
namespace Roboterverwaltung {
namespace Rumpf {
// static attributes (if any)

/**
 * 
 * @return result 
 * @param rechterArm 
 * @param linkerArm 
 * @param rechtesBein 
 * @param linkesBein 
 */
Rumpf* Rumpf::erzeugeRumpf(
		::NaoSimulation::Modellierung::Roboterverwaltung::Arm::Arm *rechterArm,
			::NaoSimulation::Modellierung::Roboterverwaltung::Arm::Arm *linkerArm,
			::NaoSimulation::Modellierung::Roboterverwaltung::Bein::Bein *rechtesBein,
			::NaoSimulation::Modellierung::Roboterverwaltung::Bein::Bein *linkesBein,
			NaoSimulation::Entwurf::NaoModel::ODE::dWorldID welt)
{
	Torso* torso = Torso::erzeugeTorso(welt);
	Becken* linkesBecken = Becken::erzeugeLinkesBecken(welt);
	Becken* rechtesBecken = Becken::erzeugeRechtesBecken(welt);
	
	Beckengelenk* beckengelenk = Beckengelenk::erzeugeBeckengelenk(torso, linkesBecken, rechtesBecken, welt);

	Hueftgelenk* linkesHueftgelenk = Hueftgelenk::erzeugeLinkesHueftgelenk(linkesBecken, linkesBein->getOberschenkel(), welt);
	Hueftgelenk* rechtesHueftgelenk = Hueftgelenk::erzeugeRechtesHueftgelenk(rechtesBecken, rechtesBein->getOberschenkel(), welt);

	Schulter* linkeSchulter = Schulter::erzeugeLinkeSchulter(torso, linkerArm->getOberarm(), welt);
	Schulter* rechteSchulter = Schulter::erzeugeRechteSchulter(torso, rechterArm->getOberarm(), welt);

	Rumpf* rumpf = new Rumpf(torso, beckengelenk, linkesBecken, rechtesBecken, linkesHueftgelenk, rechtesHueftgelenk, linkeSchulter, rechteSchulter);
	
	return rumpf;
}

Torso* Rumpf::getTorso() {
	return this->torso;
}

Beckengelenk* Rumpf::getBeckengelenk() {
	return this->beckengelenk;
}

Becken* Rumpf::getLinkesBecken() {
	return this->becken[0];
}

Becken* Rumpf::getRechtesBecken() {
	return this->becken[1];
}

Hueftgelenk* Rumpf::getLinkesHueftgelenk() {
	return this->hueftgelenk[0];
}

Hueftgelenk* Rumpf::getRechtesHueftgelenk() {
	return this->hueftgelenk[1];
}

Schulter* Rumpf::getLinkeSchulter() {
	return this->schulter[0];
}

Schulter* Rumpf::getRechteSchulter() {
	return this->schulter[1];
}

} // of namespace Rumpf
} // of namespace Roboterverwaltung
} // of namespace Modellierung
} // of namespace NaoSimulation

/************************************************************
 End of Rumpf class body
 ************************************************************/
