// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define NaoSimulation_Modellierung_Roboterverwaltung_Rumpf_Schulter_BODY

/************************************************************
 Schulter class body
 ************************************************************/

// include associated header file
#include "Schulter.h"

namespace NaoSimulation {
namespace Modellierung {
namespace Roboterverwaltung {
namespace Rumpf {

// static attributes (if any)

/**
 * 
 * @return result 
 * @param torso 
 * @param oberarm 
 */
Schulter* Schulter::erzeugeRechteSchulter(Torso* torso,
		::NaoSimulation::Modellierung::Roboterverwaltung::Arm::Oberarm* oberarm,
		NaoSimulation::Entwurf::NaoModel::ODE::dWorldID welt) {
	
	Schulter* schulter = new Schulter(torso, oberarm);

    return schulter;
}

/**
 * 
 * @return result 
 * @param torso 
 * @param oberarm 
 */
Schulter* Schulter::erzeugeLinkeSchulter(Torso* torso,
		::NaoSimulation::Modellierung::Roboterverwaltung::Arm::Oberarm* oberarm,
		NaoSimulation::Entwurf::NaoModel::ODE::dWorldID welt) {
	
	Schulter* schulter = new Schulter(torso, oberarm);

    return schulter;
}

} // of namespace Rumpf
} // of namespace Roboterverwaltung
} // of namespace Modellierung
} // of namespace NaoSimulation

/************************************************************
 End of Schulter class body
 ************************************************************/
