// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define NaoSimulation_Modellierung_Roboterverwaltung_Rumpf_Torso_BODY

/************************************************************
 Torso class body
 ************************************************************/

// include associated header file
#include "Torso.h"

// Derived includes directives

namespace NaoSimulation {
namespace Modellierung {
namespace Roboterverwaltung {
namespace Rumpf {

// static attributes (if any)

/**
 * 
 * @return result 
 */
Torso* Torso::erzeugeTorso(NaoSimulation::Entwurf::NaoModel::ODE::dWorldID welt) {
    Torso* torso = new Torso();
    torso->setHoehe(torsoParams.hoehe);
    torso->setRadius(torsoParams.radius);
    torso->setOdeKoerperteil(NaoSimulation::Entwurf::NaoModel::ODE::erzeugeODEBody(
        torsoParams.masse,
        torsoParams.position,
        torsoParams.ausrichtung,
        torsoParams.radius,
        torsoParams.hoehe,
        welt
    ));

    return torso;
}

} // of namespace Rumpf
} // of namespace Roboterverwaltung
} // of namespace Modellierung
} // of namespace NaoSimulation

/************************************************************
 End of Torso class body
 ************************************************************/
