// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef NAOSIMULATION_MODELLIERUNG_ROBOTERVERWALTUNG_BEIN_BEWEGE_BEINGELENK_H
#define NAOSIMULATION_MODELLIERUNG_ROBOTERVERWALTUNG_BEIN_BEWEGE_BEINGELENK_H

/************************************************************
 bewege_Beingelenk class header
 ************************************************************/

#include "NaoSimulation/Modellierung/Roboterverwaltung/Bein/Pkg_Bein.h"

#include "NaoSimulation/Modellierung/Roboterverwaltung/bewege_Gelenk.h"

namespace NaoSimulation {
namespace Modellierung {
namespace Roboterverwaltung {
namespace Bein {

/************************************************************/
/**
 * 
 */
class bewege_Beingelenk: public ::NaoSimulation::Modellierung::Roboterverwaltung::bewege_Gelenk {

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Bein
} // of namespace Roboterverwaltung
} // of namespace Modellierung
} // of namespace NaoSimulation

/************************************************************
 End of bewege_Beingelenk class header
 ************************************************************/

#endif
