// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define NaoSimulation_Modellierung_Roboterverwaltung_Bein_Fuss_BODY

/************************************************************
 Fuss class body
 ************************************************************/

// include associated header file
#include "Fuss.h"

// Derived includes directives

namespace NaoSimulation {
namespace Modellierung {
namespace Roboterverwaltung {
namespace Bein {

Fuss* Fuss::erzeugeLinkenFuss(NaoSimulation::Entwurf::NaoModel::ODE::dWorldID welt) {
    Fuss* fuss = new Fuss();
    fuss->setHoehe(linkerFussParams.hoehe);
    fuss->setRadius(linkerFussParams.radius);
    fuss->setOdeKoerperteil(NaoSimulation::Entwurf::NaoModel::ODE::erzeugeODEBody(
        linkerFussParams.masse,
        linkerFussParams.position,
        linkerFussParams.ausrichtung,
        linkerFussParams.radius,
        linkerFussParams.hoehe,
        welt
    ));

    return fuss;
}

Fuss* Fuss::erzeugeRechtenFuss(NaoSimulation::Entwurf::NaoModel::ODE::dWorldID welt) {
    Fuss* fuss = new Fuss();
    fuss->setHoehe(rechterFussParams.hoehe);
    fuss->setRadius(rechterFussParams.radius);
    fuss->setOdeKoerperteil(NaoSimulation::Entwurf::NaoModel::ODE::erzeugeODEBody(
        rechterFussParams.masse,
        rechterFussParams.position,
        rechterFussParams.ausrichtung,
        rechterFussParams.radius,
        rechterFussParams.hoehe,
        welt
    ));

    return fuss;
}

} // of namespace Bein
} // of namespace Roboterverwaltung
} // of namespace Modellierung
} // of namespace NaoSimulation

/************************************************************
 End of Fuss class body
 ************************************************************/
