// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef NAOSIMULATION_MODELLIERUNG_ROBOTERVERWALTUNG_BEIN_FUSS_H
#define NAOSIMULATION_MODELLIERUNG_ROBOTERVERWALTUNG_BEIN_FUSS_H

/************************************************************
 Fuss class header
 ************************************************************/

//#include "NaoSimulation/Modellierung/Roboterverwaltung/Bein/Pkg_Bein.h"

#include "../../../Entwurf/NaoModel/Koerperteile/Koerperteil.h"
#include "../../Params/RoboterParamSettings.h"


namespace NaoSimulation {
namespace Modellierung {
namespace Roboterverwaltung {
namespace Bein {

/************************************************************/
/**
 * 
 */
class Fuss: public ::NaoSimulation::Entwurf::NaoModel::Koerperteile::Koerperteil {
public:

	// Konstruktor
	Fuss() : Koerperteil() {}

	static Fuss* erzeugeLinkenFuss(NaoSimulation::Entwurf::NaoModel::ODE::dWorldID welt);

	static Fuss* erzeugeRechtenFuss(NaoSimulation::Entwurf::NaoModel::ODE::dWorldID welt);
};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Bein
} // of namespace Roboterverwaltung
} // of namespace Modellierung
} // of namespace NaoSimulation

/************************************************************
 End of Fuss class header
 ************************************************************/

#endif
