// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef NAOSIMULATION_MODELLIERUNG_ROBOTERVERWALTUNG_BEIN_KNIE_H
#define NAOSIMULATION_MODELLIERUNG_ROBOTERVERWALTUNG_BEIN_KNIE_H

/************************************************************
 Knie class header
 ************************************************************/

//#include "NaoSimulation/Modellierung/Roboterverwaltung/Bein/Pkg_Bein.h"

#include "../../../Entwurf/NaoModel/Gelenke/Scharniergelenk.h"
#include "../Freiheitsgrad.h"
#include "../../../../PrimitiveTypes/Pkg_PrimitiveTypes.h"

#include "Oberschenkel.h"
#include "Schienbein.h"

/*
namespace NaoSimulation {
namespace Modellierung {
namespace Roboterverwaltung {
namespace Bein {
class Oberschenkel;
}
}
}
}
namespace NaoSimulation {
namespace Modellierung {
namespace Roboterverwaltung {
namespace Bein {
class Schienbein;
}
}
}
}
*/
namespace NaoSimulation {
namespace Modellierung {
namespace Roboterverwaltung {
namespace Bein {

/************************************************************/
/**
 * 
 */
class Knie: public ::NaoSimulation::Entwurf::NaoModel::Gelenke::Scharniergelenk {
public:

	/**
	 * 
	 */
	::NaoSimulation::Modellierung::Roboterverwaltung::Freiheitsgrad fg;

	// Copy-Konstruktor
    Knie(Knie& knie, Oberschenkel* oberschenkel, Schienbein* schienbein):
		fg(knie.fg.getWinkel(), knie.fg.getWinkelMin(), knie.fg.getWinkelMax()),
        oberschenkel(oberschenkel),
        schienbein(schienbein) {}

    // Konstruktor
    Knie(
        ::PrimitiveTypes::Real rollWinkel,
        ::PrimitiveTypes::Real rollWinkelMin,
        ::PrimitiveTypes::Real rollWinkelMax,
        Oberschenkel* oberschenkel,
        Schienbein* schienbein
    ):
        Scharniergelenk(),
		fg(rollWinkel, rollWinkelMin, rollWinkelMax),
        oberschenkel(oberschenkel),
        schienbein(schienbein) {}
    
    static Knie* erzeugeLinkesKnie(
        Oberschenkel* oberschenkel,
        Schienbein* schienbein,
        NaoSimulation::Entwurf::NaoModel::ODE::dWorldID welt
    );

    static Knie* erzeugeRechtesKnie(
        Oberschenkel* oberschenkel, 
        Schienbein* schienbein,
        NaoSimulation::Entwurf::NaoModel::ODE::dWorldID welt
    );
	
	void rolleKnie(::PrimitiveTypes::Real /*in*/winkel);

	/**
	 * 
	 * @return result 
	 */
	::PrimitiveTypes::Real getRollWinkel();

	/**
	 * 
	 * @return result 
	 */
	::PrimitiveTypes::Real getRollWinkelMax();

	/**
	 * 
	 * @return result 
	 */
	::PrimitiveTypes::Real getRollWinkelMin();

	Oberschenkel* getOberschenkel();

	Schienbein* getSchienbein();

private:

	/**
	 * 
	 */
	Oberschenkel* oberschenkel;

	/**
	 * 
	 */
	Schienbein* schienbein;
};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Bein
} // of namespace Roboterverwaltung
} // of namespace Modellierung
} // of namespace NaoSimulation

/************************************************************
 End of Knie class header
 ************************************************************/

#endif
