// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define NaoSimulation_Modellierung_Roboterverwaltung_Bein_Oberschenkel_BODY

/************************************************************
 Oberschenkel class body
 ************************************************************/

// include associated header file
#include "Oberschenkel.h"

// Derived includes directives

namespace NaoSimulation {
namespace Modellierung {
namespace Roboterverwaltung {
namespace Bein {

Oberschenkel* Oberschenkel::erzeugeLinkenOberschenkel(NaoSimulation::Entwurf::NaoModel::ODE::dWorldID welt) {
    Oberschenkel* oberschenkel = new Oberschenkel();
    oberschenkel->setHoehe(linkerOberschenkelParams.hoehe);
    oberschenkel->setRadius(linkerOberschenkelParams.radius);
    oberschenkel->setOdeKoerperteil(NaoSimulation::Entwurf::NaoModel::ODE::erzeugeODEBody(
        linkerOberschenkelParams.masse,
        linkerOberschenkelParams.position,
        linkerOberschenkelParams.ausrichtung,
        linkerOberschenkelParams.radius,
        linkerOberschenkelParams.hoehe,
        welt
    ));

    return oberschenkel;
}

Oberschenkel* Oberschenkel::erzeugeRechtenOberschenkel(NaoSimulation::Entwurf::NaoModel::ODE::dWorldID welt) {
    Oberschenkel* oberschenkel = new Oberschenkel();
    oberschenkel->setHoehe(rechterOberschenkelParams.hoehe);
    oberschenkel->setRadius(rechterOberschenkelParams.radius);
    oberschenkel->setOdeKoerperteil(NaoSimulation::Entwurf::NaoModel::ODE::erzeugeODEBody(
        rechterOberschenkelParams.masse,
        rechterOberschenkelParams.position,
        rechterOberschenkelParams.ausrichtung,
        rechterOberschenkelParams.radius,
        rechterOberschenkelParams.hoehe,
        welt
    ));

    return oberschenkel;
}


} // of namespace Bein
} // of namespace Roboterverwaltung
} // of namespace Modellierung
} // of namespace NaoSimulation

/************************************************************
 End of Oberschenkel class body
 ************************************************************/
