// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef NAOSIMULATION_MODELLIERUNG_ROBOTERVERWALTUNG_BEIN_SCHIENBEIN_H
#define NAOSIMULATION_MODELLIERUNG_ROBOTERVERWALTUNG_BEIN_SCHIENBEIN_H

/************************************************************
 Schienbein class header
 ************************************************************/

//#include "NaoSimulation/Modellierung/Roboterverwaltung/Bein/Pkg_Bein.h"

#include "../../../Entwurf/NaoModel/Koerperteile/Koerperteil.h"
#include "../../Params/RoboterParamSettings.h"

namespace NaoSimulation {
namespace Modellierung {
namespace Roboterverwaltung {
namespace Bein {

/************************************************************/
/**
 * 
 */
class Schienbein: public ::NaoSimulation::Entwurf::NaoModel::Koerperteile::Koerperteil {
public:

	Schienbein() : Koerperteil() {}
	/**
	 * 
	 * @return result 
	 */
	static Schienbein* erzeugeLinkesSchienbein(NaoSimulation::Entwurf::NaoModel::ODE::dWorldID welt);

	static Schienbein* erzeugeRechtesSchienbein(NaoSimulation::Entwurf::NaoModel::ODE::dWorldID welt);
};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Bein
} // of namespace Roboterverwaltung
} // of namespace Modellierung
} // of namespace NaoSimulation

/************************************************************
 End of Schienbein class header
 ************************************************************/

#endif
