// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef NAOSIMULATIONMODELLENTWURF_ENTWURF_NAOMODEL_ODE_DBODYID_H
#define NAOSIMULATIONMODELLENTWURF_ENTWURF_NAOMODEL_ODE_DBODYID_H

/************************************************************
 dBodyID class header
 ************************************************************/

//#include "NaoSimulation/Entwurf/NaoModel/ODE/Pkg_ODE.h"
#include "dWorldID.h"

#include <ode/ode.h>


namespace NaoSimulation {
namespace Entwurf {
namespace NaoModel {
namespace ODE {

/************************************************************/
/**
 * 
 */
typedef dBodyID dBodyID;

dBodyID erzeugeODEBody(
    float masse,
    float position[3],
    float ausrichtung[3],
    float radius,
    float hoehe,
    NaoSimulation::Entwurf::NaoModel::ODE::dWorldID welt
);

/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/


/* Inline functions                                         */

} // of namespace ODE
} // of namespace NaoModel
} // of namespace Entwurf
} // of namespace NaoSimulation

/************************************************************
 End of dBodyID class header
 ************************************************************/

#endif
