// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef NAOSIMULATIONMODELLENTWURF_ENTWURF_NAOMODEL_ODE_DWORLDID_H
#define NAOSIMULATIONMODELLENTWURF_ENTWURF_NAOMODEL_ODE_DWORLDID_H

/************************************************************
 dWorldID class header
 ************************************************************/

//#include "NaoSimulation/Entwurf/NaoModel/ODE/Pkg_ODE.h"

#include <ode/ode.h>

namespace NaoSimulation {
namespace Entwurf {
namespace NaoModel {
namespace ODE {

/************************************************************/
/**
 * 
 */
typedef dWorldID dWorldID;


dWorldID erzeugeODEWelt();

/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace ODE
} // of namespace NaoModel
} // of namespace Entwurf
} // of namespace NaoSimulation

/************************************************************
 End of dWorldID class header
 ************************************************************/

#endif
