// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define NaoSimulation_Entwurf_NaoController_Command_BeinCommand_RKnieNickenCC_BODY

/************************************************************
 RKnieNickenCC class body
 ************************************************************/

// include associated header file
#include "NaoSimulation/Entwurf/NaoController/Command/BeinCommand/RKnieNickenCC.h"

// Derived includes directives

namespace NaoSimulation {
namespace Entwurf {
namespace NaoController {
namespace Command {
namespace BeinCommand {

void RKnieNickenCC::execute() {
    knie->rolleKnie(winkel);
}

void RKnieNickenCC::setzeParameter(::PrimitiveTypes::Real winkel) {
    this->winkel = winkel;
}

}// of namespace BeinCommand
} // of namespace Command
} // of namespace NaoController
} // of namespace Entwurf
} // of namespace NaoSimulation

/************************************************************
 End of RKnieNickenCC class body
 ************************************************************/
