// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef NAOSIMULATIONMODELLENTWURF_ENTWURF_NAOCONTROLLER_COMMAND_BEINCOMMAND_RKNIENICKENCC_H
#define NAOSIMULATIONMODELLENTWURF_ENTWURF_NAOCONTROLLER_COMMAND_BEINCOMMAND_RKNIENICKENCC_H

/************************************************************
 RKnieNickenCC class header
 ************************************************************/

#include "NaoSimulation/Entwurf/NaoController/Command/BeinCommand/Pkg_BeinCommand.h"

#include "NaoSimulation/Entwurf/NaoController/Command/GelenkCommand.h"
#include "NaoSimulation/Modellierung/Roboterverwaltung/Bein/Knie.h"

namespace NaoSimulation {
namespace Entwurf {
namespace NaoController {
namespace Command {
namespace BeinCommand {

/************************************************************/
/**
 * 
 */
class RKnieNickenCC: public ::NaoSimulation::Entwurf::NaoController::Command::GelenkCommand {
private:
	::NaoSimulation::Modellierung::Roboterverwaltung::Bein::Knie* knie;

	::PrimitiveTypes::Real winkel;
public:
	RKnieNickenCC(::NaoSimulation::Modellierung::Roboterverwaltung::Bein::Knie* knie):
		knie(knie), winkel(0.0) {}

	void execute();

	void setzeParameter(::PrimitiveTypes::Real winkel);

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace BeinCommand
} // of namespace Command
} // of namespace NaoController
} // of namespace Entwurf
} // of namespace NaoSimulation

/************************************************************
 End of RKnieNickenCC class header
 ************************************************************/

#endif
