// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define NaoSimulation_Entwurf_NaoController_Command_BeinCommand_RSprunggelenkNickenCC_BODY

/************************************************************
 RSprunggelenkNickenCC class body
 ************************************************************/

// include associated header file
#include "NaoSimulation/Entwurf/NaoController/Command/BeinCommand/RSprunggelenkNickenCC.h"

// Derived includes directives

namespace NaoSimulation {
namespace Entwurf {
namespace NaoController {
namespace Command {
namespace BeinCommand {

void RSprunggelenkNickenCC::execute() {
    sprunggelenk->nickeSprunggelenk(winkel);
}

void RSprunggelenkNickenCC::setzeParameter(::PrimitiveTypes::Real winkel) {
    this->winkel = winkel;
}

}// of namespace BeinCommand
} // of namespace Command
} // of namespace NaoController
} // of namespace Entwurf
} // of namespace NaoSimulation

/************************************************************
 End of RSprunggelenkNickenCC class body
 ************************************************************/
