// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef NAOSIMULATIONMODELLENTWURF_ENTWURF_NAOCONTROLLER_COMMAND_BEINCOMMAND_RSPRUNGGELENKNICKENCC_H
#define NAOSIMULATIONMODELLENTWURF_ENTWURF_NAOCONTROLLER_COMMAND_BEINCOMMAND_RSPRUNGGELENKNICKENCC_H

/************************************************************
 RSprunggelenkNickenCC class header
 ************************************************************/

#include "NaoSimulation/Entwurf/NaoController/Command/BeinCommand/Pkg_BeinCommand.h"

#include "NaoSimulation/Entwurf/NaoController/Command/GelenkCommand.h"
#include "NaoSimulation/Modellierung/Roboterverwaltung/Bein/Sprunggelenk.h"

namespace NaoSimulation {
namespace Entwurf {
namespace NaoController {
namespace Command {
namespace BeinCommand {

/************************************************************/
/**
 * 
 */
class RSprunggelenkNickenCC: public ::NaoSimulation::Entwurf::NaoController::Command::GelenkCommand {
private:
	::NaoSimulation::Modellierung::Roboterverwaltung::Bein::Sprunggelenk* sprunggelenk;

::PrimitiveTypes::Real winkel;
public:
	RSprunggelenkNickenCC(::NaoSimulation::Modellierung::Roboterverwaltung::Bein::Sprunggelenk* sprunggelenk):
		sprunggelenk(sprunggelenk), winkel(0.0) {}

	void execute();

	void setzeParameter(::PrimitiveTypes::Real winkel);	
};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace BeinCommand
} // of namespace Command
} // of namespace NaoController
} // of namespace Entwurf
} // of namespace NaoSimulation

/************************************************************
 End of RSprunggelenkNickenCC class header
 ************************************************************/

#endif
