// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef NAOSIMULATIONMODELLENTWURF_ENTWURF_NAOCONTROLLER_COMMAND_INITCOMMAND_INITCOMMANDCC_H
#define NAOSIMULATIONMODELLENTWURF_ENTWURF_NAOCONTROLLER_COMMAND_INITCOMMAND_INITCOMMANDCC_H

/************************************************************
 InitCommandCC class header
 ************************************************************/

#include "NaoSimulation/Entwurf/NaoController/Command/InitCommand/Pkg_InitCommand.h"

#include "NaoSimulation/Entwurf/NaoController/Command/Command.h"
#include "NaoSimulation/Entwurf/NaoModel/Welt/Welt.h"

namespace NaoSimulation {
namespace Entwurf {
namespace NaoController {
namespace Command {
namespace InitCommand {

/************************************************************/
/**
 * 
 */
class InitCommandCC: public ::NaoSimulation::Entwurf::NaoController::Command::Command {
public:

	/**
	 * 
	 */
	::NaoSimulation::Entwurf::NaoModel::Welt::Welt welt;

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace InitCommand
} // of namespace Command
} // of namespace NaoController
} // of namespace Entwurf
} // of namespace NaoSimulation

/************************************************************
 End of InitCommandCC class header
 ************************************************************/

#endif
