// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef NAOSIMULATIONMODELLENTWURF_ENTWURF_NAOVIEW_ROBOTERANZEIGE_ROBOTERZEICHNER_H
#define NAOSIMULATIONMODELLENTWURF_ENTWURF_NAOVIEW_ROBOTERANZEIGE_ROBOTERZEICHNER_H

/************************************************************
 RoboterZeichner class header
 ************************************************************/

#include "NaoSimulation/Entwurf/NaoView/Roboteranzeige/Pkg_Roboteranzeige.h"

#include "NaoSimulation/Entwurf/NaoView/Roboteranzeige/Armanzeige/ArmZeichner.h"
#include "NaoSimulation/Entwurf/NaoView/Roboteranzeige/Beinanzeige/BeinZeichner.h"
#include "NaoSimulation/Entwurf/NaoView/Roboteranzeige/Kopfanzeige/KopfZeichner.h"
#include "Rumpfanzeige/RumpfZeichner.h"
#include "NaoSimulation/Modellierung/Roboterverwaltung/Roboter.h"

namespace NaoSimulation {
namespace Entwurf {
namespace NaoView {
namespace Roboteranzeige {

/************************************************************/
/**
 * 
 */
class RoboterZeichner {
public:
	static void zeichneRoboter(::NaoSimulation::Modellierung::Roboterverwaltung::Roboter* roboter);
};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Roboteranzeige
} // of namespace NaoView
} // of namespace Entwurf
} // of namespace NaoSimulation

/************************************************************
 End of RoboterZeichner class header
 ************************************************************/

#endif
