// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#include "Rumpfanzeige/RumpfZeichner.h"
#define NaoSimulation_Entwurf_NaoView_Roboteranzeige_RoboterZeichner_BODY

/************************************************************
 RoboterZeichner class body
 ************************************************************/

// include associated header file
#include "NaoSimulation/Entwurf/NaoView/Roboteranzeige/RoboterZeichner.h"

// Derived includes directives

namespace NaoSimulation {
namespace Entwurf {
namespace NaoView {
namespace Roboteranzeige {

void RoboterZeichner::zeichneRoboter(::NaoSimulation::Modellierung::Roboterverwaltung::Roboter* roboter) {
	// zeichne linkes Bein
	Beinanzeige::BeinZeichner::zeichneBein(roboter->getLinkesBein());
	// zeichne rechtes Bein
	Beinanzeige::BeinZeichner::zeichneBein(roboter->getRechtesBein());
	// zeichne linken Arm
	Armanzeige::ArmZeichner::zeichneArm(roboter->getLinkenArm());
	// zeichne rechten Arm
	Armanzeige::ArmZeichner::zeichneArm(roboter->getRechtenArm());
	// zeichne Rumpf
	Rumpfanzeige::RumpfZeichner::zeichneRumpf(roboter->getRumpf());
	// zeichne Kopf
	Kopfanzeige::KopfZeichner::zeichneKopf(roboter->getKopf());
}

} // of namespace Roboteranzeige
} // of namespace NaoView
} // of namespace Entwurf
} // of namespace NaoSimulation

/************************************************************
 End of RoboterZeichner class body
 ************************************************************/
