// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define NaoSimulation_Entwurf_NaoModel_Welt_Welt_BODY

/************************************************************
 Welt class body
 ************************************************************/

#include <ode/ode.h>

// include associated header file
#include "NaoSimulation/Entwurf/NaoModel/Welt/Welt.h"


namespace NaoSimulation {
namespace Entwurf {
namespace NaoModel {
namespace Welt {


dWorldID Welt::getODEWelt() {
    return welt;
}

::NaoSimulation::Modellierung::Roboterverwaltung::Roboter* Welt::getRoboter() {
    return roboter;
}

void Welt::setODEWelt(dWorldID welt) {
    this->welt = welt;
}

void Welt::setRoboter(::NaoSimulation::Modellierung::Roboterverwaltung::Roboter* roboter) {
    this->roboter = roboter;
}

} // of namespace Welt
} // of namespace NaoModel
} // of namespace Entwurf
} // of namespace NaoSimulation

/************************************************************
 End of Welt class body
 ************************************************************/
