// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define NaoSimulation_Entwurf_NaoView_WeltZeichner_BODY

/************************************************************
 WeltZeichner class body
 ************************************************************/

// include associated header file
#include "NaoSimulation/Entwurf/NaoView/WeltZeichner.h"

//#define DRAWSTUFF_TEXTURE_PATH "/usr/local/include/drawstuff/textures"

namespace NaoSimulation {
namespace Entwurf {
namespace NaoView {

NaoSimulation::Entwurf::NaoModel::Welt::Welt* WeltZeichner::welt = nullptr;

WeltZeichner::WeltZeichner() {
	// Erzeuge eine Drawstuff-Fkt, die in einem extra Thread laeuft
	dsFunctions* fn = (dsFunctions*) malloc(sizeof(dsFunctions) * 1); 
    // Version von Drawstuff
    fn->version          = DS_VERSION;
    // Start-Fkt
    fn->start            = &WeltZeichner::DRAWSTUFF_start;
    // Schritt-Fkt
    fn->step             = &WeltZeichner::DRAWSTUFF_simLoop;
    // Kommando-Fkt
    fn->command          = &WeltZeichner::DRAWSTUFF_command;
    // Stop-Fkt
    fn->stop             = &WeltZeichner::DRAWSTUFF_stop;
    // Pfad zu den Drawstuff-Texturen
    fn->path_to_textures = DRAWSTUFF_TEXTURE_PATH;

    // Starte die DRAWSTUFF-Schleife in einem eigenen Thread
    grLopp_thread = new std::thread(dsSimulationLoop, 0, nullptr, 800, 600, fn);
}

void WeltZeichner::grLoop() {
    return ;
}

void WeltZeichner::ueberschreibeWelt(::NaoSimulation::Entwurf::NaoModel::Welt::Welt* welt) {
	WeltZeichner::welt = welt;
}

void WeltZeichner::zeichneWelt(::NaoSimulation::Entwurf::NaoModel::Welt::Welt* welt) {
	// Zeichne alle Objekte in der Welt (aktuell nur der Roboter)
	Roboteranzeige::RoboterZeichner::zeichneRoboter(welt->getRoboter());
}

void WeltZeichner::DRAWSTUFF_simLoop(int pause) {
	// Wenn die Grafiksimulation nicht pausiert
	if(!pause && welt != nullptr) {
		// zeichne die gesamte Welt
		WeltZeichner::zeichneWelt(WeltZeichner::welt);
	}
}

void WeltZeichner::DRAWSTUFF_stop() {
	return ;
}

void WeltZeichner::DRAWSTUFF_start() {
	// Kamera-Position im Raum
    static float xyz[3] = {0.0,20.0,10.0};
    // Blickrichtung der Kamera
    static float hpr[3] = {270.0,0.0,0.0};
    // initialisiere Kamera (Viewpoint) mit Position und Blickrichtung
    dsSetViewpoint (xyz,hpr);
}

void WeltZeichner::DRAWSTUFF_command(int key) {
	return ;
}

} // of namespace NaoView
} // of namespace Entwurf
} // of namespace NaoSimulation

/************************************************************
 End of WeltZeichner class body
 ************************************************************/
