// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define NaoSimulation_Entwurf_NaoModel_Gelenke_ZweifachScharniergelenk_BODY

/************************************************************
 ZweifachScharniergelenk class body
 ************************************************************/

// include associated header file
#include "NaoSimulation/Entwurf/NaoModel/Gelenke/ZweifachScharniergelenk.h"

// Derived includes directives

namespace NaoSimulation {
namespace Entwurf {
namespace NaoModel {
namespace Gelenke {

::NaoSimulation::Entwurf::NaoModel::ODE::dJointID ZweifachScharniergelenk::getODEGelenk1() {
    return odeGelenk1;
}

::NaoSimulation::Entwurf::NaoModel::ODE::dJointID ZweifachScharniergelenk::getODEGelenk2() {
    return odeGelenk2;
}

::NaoSimulation::Entwurf::NaoModel::ODE::dBodyID ZweifachScharniergelenk::getODEZwischenkoerper() {
    return odeZwischenkoerper;
}

void ZweifachScharniergelenk::setODEGelenk1(::NaoSimulation::Entwurf::NaoModel::ODE::dJointID gelenk) {
    odeGelenk1 = gelenk;
}

void ZweifachScharniergelenk::setODEGelenk2(::NaoSimulation::Entwurf::NaoModel::ODE::dJointID gelenk) {
    odeGelenk2 = gelenk;
}

void ZweifachScharniergelenk::setODEZwischenkoerper(::NaoSimulation::Entwurf::NaoModel::ODE::dBodyID koerper) {
    odeZwischenkoerper = koerper;
}

}// of namespace Gelenke
} // of namespace NaoModel
} // of namespace Entwurf
} // of namespace NaoSimulation

/************************************************************
 End of ZweifachScharniergelenk class body
 ************************************************************/
