// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define NaoSimulation_Entwurf_NaoController_Command_KopfCommand_HalsgelenkNickenCC_BODY

/************************************************************
 HalsgelenkNickenCC class body
 ************************************************************/

// include associated header file
#include "NaoSimulation/Entwurf/NaoController/Command/KopfCommand/HalsgelenkNickenCC.h"

// Derived includes directives

namespace NaoSimulation {
namespace Entwurf {
namespace NaoController {
namespace Command {
namespace KopfCommand {

void HalsgelenkNickenCC::execute() {
    halsgelenk->nickeHalsgelenk(winkel);
}

void HalsgelenkNickenCC::setzeParameter(::PrimitiveTypes::Real winkel) {
    this->winkel = winkel;
}

}// of namespace KopfCommand
} // of namespace Command
} // of namespace NaoController
} // of namespace Entwurf
} // of namespace NaoSimulation

/************************************************************
 End of HalsgelenkNickenCC class body
 ************************************************************/
