// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define NaoSimulation_Entwurf_NaoController_Command_KopfCommand_HalsgelenkGierenCC_BODY

/************************************************************
 HalsgelenkGierenCC class body
 ************************************************************/

// include associated header file
#include "NaoSimulation/Entwurf/NaoController/Command/KopfCommand/HalsgelenkGierenCC.h"

// Derived includes directives

namespace NaoSimulation {
namespace Entwurf {
namespace NaoController {
namespace Command {
namespace KopfCommand {

// static attributes (if any)

void HalsgelenkGierenCC::execute() {
    halsgelenk->giereHalsgelenk(winkel);
}

void HalsgelenkGierenCC::setzeParameter(::PrimitiveTypes::Real winkel) {
    this->winkel = winkel;
}

} // of namespace KopfCommand
} // of namespace Command
} // of namespace NaoController
} // of namespace Entwurf
} // of namespace NaoSimulation

/************************************************************
 End of HalsgelenkGierenCC class body
 ************************************************************/
