// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef NAOSIMULATION_ENTWURF_NAOVIEW_ROBOTERANZEIGE_RUMPFANZEIGE_RUMPFZEICHNER_H
#define NAOSIMULATION_ENTWURF_NAOVIEW_ROBOTERANZEIGE_RUMPFANZEIGE_RUMPFZEICHNER_H

/************************************************************
 RumpfZeichner class header
 ************************************************************/

//#include "NaoSimulation/Entwurf/NaoView/Roboteranzeige/Rumpfanzeige/Pkg_Rumpfanzeige.h"

#include "../Koerperteilanzeige/KoerperteilZeichner.h"

#include "../../../../Modellierung/Roboterverwaltung/Rumpf/Rumpf.h"
#include "../../../../Modellierung/Roboterverwaltung/Rumpf/Torso.h"
#include "../../../../Modellierung/Roboterverwaltung/Rumpf/Becken.h"

/*
namespace NaoSimulation {
namespace Modellierung {
namespace Roboterverwaltung {
namespace Rumpf {
class Rumpf;
}
}
}
}
*/
namespace NaoSimulation {
namespace Entwurf {
namespace NaoView {
namespace Roboteranzeige {
namespace Rumpfanzeige {

/************************************************************/
/**
 * 
 */
class RumpfZeichner {
public:

	/**
	 * 
	 * @param rumpf 
	 */
	static void zeichneRumpf(
			::NaoSimulation::Modellierung::Roboterverwaltung::Rumpf::Rumpf* rumpf);

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Rumpfanzeige
} // of namespace Roboteranzeige
} // of namespace NaoView
} // of namespace Entwurf
} // of namespace NaoSimulation

/************************************************************
 End of RumpfZeichner class header
 ************************************************************/

#endif
