// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define NaoSimulation_Entwurf_NaoView_Roboteranzeige_Rumpfanzeige_RumpfZeichner_BODY

/************************************************************
 RumpfZeichner class body
 ************************************************************/

// include associated header file
#include "RumpfZeichner.h"


namespace NaoSimulation {
namespace Entwurf {
namespace NaoView {
namespace Roboteranzeige {
namespace Rumpfanzeige {

// static attributes (if any)

/**
 * 
 * @param rumpf 
 */
void RumpfZeichner::zeichneRumpf(
		::NaoSimulation::Modellierung::Roboterverwaltung::Rumpf::Rumpf* rumpf) {
	// zeichne Torso
	Koerperteilanzeige::KoerperteilZeichner::zeichneKoerperteil(*rumpf->getTorso());
	// zeichne linke(n) Becken(knochen)
	Koerperteilanzeige::KoerperteilZeichner::zeichneKoerperteil(*rumpf->getLinkesBecken());
	// zeichne rechte(n) Becken(knochen)
	Koerperteilanzeige::KoerperteilZeichner::zeichneKoerperteil(*rumpf->getRechtesBecken());
	
}

} // of namespace Rumpfanzeige
} // of namespace Roboteranzeige
} // of namespace NaoView
} // of namespace Entwurf
} // of namespace NaoSimulation

/************************************************************
 End of RumpfZeichner class body
 ************************************************************/
