// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef NAOSIMULATIONMODELLENTWURF_ENTWURF_NAOMODEL_KOERPERTEILE_KOERPERTEIL_H
#define NAOSIMULATIONMODELLENTWURF_ENTWURF_NAOMODEL_KOERPERTEILE_KOERPERTEIL_H

/************************************************************
 Koerperteil class header
 ************************************************************/

//#include "NaoSimulation/Entwurf/NaoModel/Koerperteile/Pkg_Koerperteile.h"

#include "../ODE/dBodyID.h"
#include "../../../../PrimitiveTypes/Pkg_PrimitiveTypes.h"

namespace NaoSimulation {
namespace Entwurf {
namespace NaoModel {
namespace Koerperteile {

/************************************************************/
/**
 * 
 */
class Koerperteil {
protected:
	::PrimitiveTypes::Real hoehe;

	::PrimitiveTypes::Real radius;

	::NaoSimulation::Entwurf::NaoModel::ODE::dBodyID odeKoerperteil;
public:
	// Initialisierung des Koerperteils
	// Parameter muessen in dem jeweiligen Koerperteil selbst festgelegt werden!
	Koerperteil() : hoehe(0.0), radius(0.0), odeKoerperteil(nullptr) {}

	::PrimitiveTypes::Real getRadius();

	::PrimitiveTypes::Real getHoehe();
	
	::NaoSimulation::Entwurf::NaoModel::ODE::dBodyID getOdeKoerperteil();

	void setOdeKoerperteil(::NaoSimulation::Entwurf::NaoModel::ODE::dBodyID koerperteil);

	void setRadius(::PrimitiveTypes::Real radius);

	void setHoehe(::PrimitiveTypes::Real hoehe);
};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Koerperteile
} // of namespace NaoModel
} // of namespace Entwurf
} // of namespace NaoSimulation

/************************************************************
 End of Koerperteil class header
 ************************************************************/

#endif
